id: ssh_file_owner_sshd_config
title: Verify Owner on SSH Server config file
discussion: |
  Service configuration files enable or disable features of their respective services that if configured incorrectly can lead to insecure and vulnerable configurations. Therefore, service configuration files should be owned by the correct group to prevent unauthorized changes.
references:
  disa:
    cci:
      - CCI-000366
    srg:
      - SRG-OS-000480-GPOS-00227
    disa_stig:
      '9':
        - RHEL-09-255110
  nist:
    800-53r5:
      - AC-6
      - CM-6
    cce:
      '10':
        - CCE-89829-6
      '8':
        - CCE-82898-8
      '9':
        - CCE-90821-0
os_specifics:
  rhel:
    enforcement_info:
      check: /usr/bin/stat -c %g /etc/ssh/sshd_config
      result: 
        integer: 0
      fix: |
        # Remediation is applicable only in certain platforms
        if rpm --quiet -q kernel; then

        chown 0 /etc/ssh/sshd_config

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi
    '10':
      severity: medium
      benchmarks:
        - disa_stig
    '8':
      severity: medium
      benchmarks:
        - disa_stig
    '9':
      severity: medium
      benchmarks:
        - disa_stig
  ubuntu:
    enforcement_info:
      check: /usr/bin/stat -c %g /etc/ssh/sshd_config
      result: 
        integer: 0
      fix: |
        # Remediation is applicable only in certain platforms
        if dpkg-query --show --showformat='${db:Status-Status}
        ' 'linux-base' 2>/dev/null | grep -q ^installed; then

        chown 0 /etc/ssh/sshd_config

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi
    '2004':
      severity: medium
      benchmarks:
        - disa_stig
    '2204':
      severity: medium
      benchmarks:
        - disa_stig
    '2404':
      severity: medium
      benchmarks:
        - disa_stig
tags:
  - 800-53r5_high
  - 800-53r5_low
  - 800-53r5_moderate
  - client
  - server
