from dataclasses import dataclass, field
from typing import Optional

from scap.variable_type_2 import VariableType2

__NAMESPACE__ = "http://scap.nist.gov/schema/ocil/2.0"


@dataclass
class LocalVariableType(VariableType2):
    """The LocalVariableType type defines structures containing a value determined
    during evaluation.

    The value is determined based on the answer to the linked question.
    If one or more set elements are present, the value is computed based
    on those set elements.  The value stored in the first set element
    that produces a match pattern is used. If none of the set elements
    have a pattern that matches the response, then an error result is
    generated. If no set element is provided, the value used will be the
    same as the answer, with a few exceptions. The mappings are listed
    below. 1) If the question is a boolean question and the variable
    data type is NUMERIC, then the value based on the answer must be 1
    for true and 0 for false. 2) If the question is a boolean question
    and the variable data type is TEXT, then the value is determined by
    the question's model as follows: a) MODEL_YES_NO: the value must be
    yes if true or no if false. b) MODEL_TRUE_FALSE: the value must be
    true if true or false if false. 3) If the question is a choice
    question, the variable data type must be TEXT and the value must be
    set to the text value of the choice. 4) If the question is a numeric
    question, the variable data type must be NUMERIC and the value must
    be set to the value of the answer. 5) If the question is a string
    question, the variable data type must be TEXT and the value must be
    set to the value of the answer. If a local variable is referenced
    and the value cannot be determined, then the referencing question or
    test action should cause an ERROR result to be generated by all
    referencing test actions.

    :ivar set: The set element contains information describing how to
        compute the value to be stored on the variable. It holds the
        patterns, choice_refs, range or boolean values to be matched
        with the answer to the linked question; and the appropriate
        value to be stored on the variable based on the match.
    :ivar question_ref: The question_ref attribute holds the unique
        identifier of the question in which the variable is linked.
    """

    set: Optional[object] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://scap.nist.gov/schema/ocil/2.0",
        },
    )
    question_ref: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "pattern": r"ocil:[A-Za-z0-9_\-\.]+:question:[1-9][0-9]*",
        },
    )
