from dataclasses import dataclass, field
from typing import Optional

from scap.msg_sev_enum_type import MsgSevEnumType

__NAMESPACE__ = "http://checklists.nist.gov/xccdf/1.2"


@dataclass
class MessageType2:
    """Type for a message generated by the checking engine or XCCDF tool during
    &lt;xccdf:Benchmark&gt; testing.

    The message is contained in string format in the body of the
    element.

    :ivar value:
    :ivar severity: Denotes the seriousness of the message.
    """

    class Meta:
        name = "messageType"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    severity: Optional[MsgSevEnumType] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )
