id: os_apparmor_configured
title: Ensure AppArmor is Active and Configured
discussion: |
  Using a whitelist provides a configuration management method for allowing
  the execution of only authorized software. Using only authorized software
  decreases risk by limiting the number of potential vulnerabilities.


  The organization must identify authorized software programs and permit
  execution of authorized software by adding each authorized program to the
  "pam_apparmor" exception policy. The process used to identify software
  programs that are authorized to execute on organizational information
  systems is commonly referred to as whitelisting.


  Verification of whitelisted software occurs prior to execution or at system
  startup.


  Users' home directories/folders may contain information of a sensitive
  nature. Nonprivileged users should coordinate any sharing of information
  with a System Administrator (SA) through shared resources.


  Apparmor can confine users to their home directory, not allowing them to
  make any changes outside of their own home directories. Confining users to
  their home directory will minimize the risk of sharing information.
references:
  disa:
    cci:
      - CCI-001764
      - CCI-001774
      - CCI-002165
      - CCI-002233
      - CCI-002235
    srg:
      - SRG-OS-000312-GPOS-00122
      - SRG-OS-000312-GPOS-00123
      - SRG-OS-000312-GPOS-00124
      - SRG-OS-000324-GPOS-00125
      - SRG-OS-000326-GPOS-00126
      - SRG-OS-000370-GPOS-00155
      - SRG-OS-000480-GPOS-00227
      - SRG-OS-000480-GPOS-00230
      - SRG-OS-000480-GPOS-00231
      - SRG-OS-000480-GPOS-00232
    disa_stig:
      '2004':
        - UBTU-20-010439
      '2204':
        - UBTU-22-431015
  nist:
    800-53r4:
      - AC-3
      - AC-6
      - CM-6
      - CM-7
      - SC-7
os_specifics:
  ubuntu:
    check: $OS_VALUE
    result: $OS_VALUE
    fix: $OS_VALUE
    '2004':
      severity: medium
      benchmarks:
        - disa_stig
        - nist_800-53r4
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ]; then

        # Enable apparmor
        /usr/bin/systemctl enable "apparmor"
        if [[ $(/usr/bin/systemctl is-system-running) != "offline" ]]; then
        /usr/bin/systemctl start "apparmor"
        fi
        # The service may not be running because it has been started and failed,
        # so let's reset the state so OVAL checks pass.
        # Service should be 'inactive', not 'failed' after reboot though.
        if /usr/bin/systemctl --failed | grep -q "apparmor"; then
            /usr/bin/systemctl reset-failed "apparmor"
        fi

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
    '2204':
      severity: medium
      benchmarks:
        - disa_stig
        - nist_800-53r4
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ]; then

        # Enable apparmor
        /usr/bin/systemctl enable "apparmor"
        if [[ $(/usr/bin/systemctl is-system-running) != "offline" ]]; then
        /usr/bin/systemctl start "apparmor"
        fi
        # The service may not be running because it has been started and failed,
        # so let's reset the state so OVAL checks pass.
        # Service should be 'inactive', not 'failed' after reboot though.
        if /usr/bin/systemctl --failed | grep -q "apparmor"; then
            /usr/bin/systemctl reset-failed "apparmor"
        fi

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
tags:
  - 800-53r4_high
  - 800-53r4_low
  - 800-53r4_moderate
