id: os_file_ownership_audit_configuration
title: Audit Configuration Files Must Be Owned By Root
discussion: |
  Without the capability to restrict which roles and individuals can
  select which events are audited, unauthorized personnel may be able
  to prevent the auditing of critical events.
  Misconfigured audits may degrade the system's performance by
  overwhelming the audit log. Misconfigured audits may also make it more
  difficult to establish, correlate, and investigate the events relating
  to an incident or identify those responsible for one.
references:
  disa:
    cci:
      - CCI-000171
    srg:
      - SRG-OS-000063-GPOS-00032
    disa_stig:
      'rhel_9':
        - RHEL-09-232103
      'ubuntu_2004':
        - UBTU-20-010134
      'ubuntu_2204':
        - UBTU-22-653070
  nist:
    cce:
      'rhel_10':
        - CCE-88877-6
      'rhel_8':
        - CCE-86406-6
      'rhel_9':
        - CCE-86445-4
os_specifics:
  rhel:
    check: $OS_VALUE
    result: $OS_VALUE
    fix: $OS_VALUE
    '10':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if rpm --quiet -q audit && rpm --quiet -q kernel; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
    '8':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if rpm --quiet -q audit && rpm --quiet -q kernel; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
    '9':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if rpm --quiet -q audit && rpm --quiet -q kernel; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
  ubuntu:
    check: $OS_VALUE
    result: $OS_VALUE
    fix: $OS_VALUE
    '2004':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if dpkg-query --show --showformat='${db:Status-Status}
        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
    '2204':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if dpkg-query --show --showformat='${db:Status-Status}
        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
    '2404':
      severity: medium
      benchmarks:
        - disa_stig
      enforcement_info:
        - N/A
      result:
        integer: 0
      fix: |
        [source,bash]
        ---
        # Remediation is applicable only in certain platforms
        if dpkg-query --show --showformat='${db:Status-Status}
        ' 'linux-base' 2>/dev/null | grep -q ^installed && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q '^installed'; then

        find -L /etc/audit/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*audit(\.rules|d\.conf)$' -exec chown -L 0 {} \;

        find -L /etc/audit/rules.d/ -maxdepth 1 -type f ! -uid 0 -regextype posix-extended -regex '^.*\.rules$' -exec chown -L 0 {} \;

        else
            >&2 echo 'Remediation is not applicable, nothing was done'
        fi

        ---
tags:
  - cis_lvl2
  - client
  - server
