id: os_group_ownership_audit_configuration
title: "Verify Group Ownership Permissions on /etc/audit/*"
discussion: |
  Without the capability to restrict which roles and individuals can select which events are audited, unauthorized personnel may be able to prevent the auditing of critical events.
check: |
  $OS_VALUE
result:
  integer: 1
fix: |
  $OS_VALUE
references:
  cce:
    - $OS_VALUE
  cci:
    - CCI-000171
  800-53r5:
    - N/A
  srg:
    - SRG-OS-000063-GPOS-00032
  disa_stig:
    - UBTU-20-010135
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - client
  - server
severity: "medium"
os_specifics:
  ubuntu:
    '2204':
      references:
        cce:
          - N/A
        disa_stig:
          - N/A
        check: |
          GROUPMATCH=$(stat -c "%G" /etc/audit/* | grep -v "root" | wc -l)
          if [ $GROUPMATCH -e 0 ]; then
             echo "PASS"
          else
             echo "FAIL"
          fi
        fix: |
          [source,bash]
          ---
            # Remediation is applicable only in certain platforms
            if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ] && dpkg-query --show --showformat='${db:Status-Status}\n' 'auditd' 2>/dev/null | grep -q installed; then

            find /etc/audit/ -maxdepth 1 -type f ! -gid 0 -regex '^audit(\.rules|d\.conf)$' -exec chgrp 0 {} \;

            find /etc/audit/rules.d/ -maxdepth 1 -type f ! -gid 0 -regex '^.*\.rules$' -exec chgrp 0 {} \;

            else
                >&2 echo 'Remediation is not applicable, nothing was done'
            fi
          ---
