from oval.definitions.cpe_dictionary_2_3 import (
    CheckType as CpeDictionary3CheckType,
)
from oval.definitions.cpe_dictionary_2_3 import (
    CpeItem,
    CpeList,
    ListType,
    ReferencesType,
)
from oval.definitions.cpe_dictionary_2_3 import (
    GeneratorType as CpeDictionary23GeneratorType,
)
from oval.definitions.cpe_dictionary_2_3 import (
    ItemType as CpeDictionary23ItemType,
)
from oval.definitions.cpe_dictionary_2_3 import (
    NotesType as CpeDictionary23NotesType,
)
from oval.definitions.cpe_dictionary_2_3 import (
    TextType as DictionaryTextType,
)
from oval.definitions.cpe_language_2_3 import (
    CheckFactRef,
    CheckFactRefType,
    CpefactRefType,
    FactRef,
    FactRefType,
    LogicalTest,
    LogicalTestType,
    Platform,
    PlatformBaseType,
    PlatformConfiguration,
    PlatformSpecification,
    PlatformSpecificationType,
    PlatformType,
)
from oval.definitions.cpe_language_2_3 import (
    OperatorEnumeration as CpeLanguage23OperatorEnumeration,
)
from oval.definitions.cpe_language_2_3 import (
    TextType as LanguageTextType,
)
from oval.definitions.evaluation_ids import EvalutationDefinitionIds
from oval.definitions.independent_definitions_schema import (
    EntityObjectEngineType,
    EntityObjectHashTypeType,
    EntityObjectShellType,
    EntityObjectVariableRefType,
    EntityStateEngineType,
    EntityStateFamilyType,
    EntityStateHashTypeType,
    EntityStateLdaptypeType,
    EntityStateShellType,
    EntityStateVariableRefType,
    Environmentvariable58Object,
    Environmentvariable58State,
    Environmentvariable58Test,
    EnvironmentvariableObject,
    EnvironmentvariableState,
    EnvironmentvariableTest,
    FamilyObject,
    FamilyState,
    FamilyTest,
    Filehash58Object,
    Filehash58State,
    Filehash58Test,
    FilehashObject,
    FilehashState,
    FilehashTest,
    Ldap57Object,
    Ldap57State,
    Ldap57Test,
    LdapBehaviors,
    LdapBehaviorsScope,
    LdapObject,
    LdapState,
    LdapTest,
    ShellcommandObject,
    ShellcommandState,
    ShellcommandTest,
    Sql57Object,
    Sql57State,
    Sql57Test,
    Sql512Object,
    Sql512State,
    Sql512Test,
    SqlObject,
    SqlState,
    SqlTest,
    Textfilecontent54Behaviors,
    Textfilecontent54Object,
    Textfilecontent54State,
    Textfilecontent54Test,
    TextfilecontentObject,
    TextfilecontentState,
    TextfilecontentTest,
    UnknownTest,
    VariableObject,
    VariableState,
    VariableTest,
    XmlfilecontentObject,
    XmlfilecontentState,
    XmlfilecontentTest,
    YamlfilecontentObject,
    YamlfilecontentState,
    YamlfilecontentTest,
)
from oval.definitions.independent_definitions_schema import (
    EntityStateWindowsViewType as IndependentEntityStateWindowsViewType,
)
from oval.definitions.independent_definitions_schema import (
    FileBehaviors as IndependentFileBehaviors,
)
from oval.definitions.independent_definitions_schema import (
    FileBehaviorsRecurse as IndependentFileBehaviorsRecurse,
)
from oval.definitions.independent_definitions_schema import (
    FileBehaviorsRecurseDirection as IndependentFileBehaviorsRecurseDirection,
)
from oval.definitions.independent_definitions_schema import (
    FileBehaviorsRecurseFileSystem as IndependentFileBehaviorsRecurseFileSystem,
)
from oval.definitions.independent_definitions_schema import (
    FileBehaviorsWindowsView as IndependentFileBehaviorsWindowsView,
)
from oval.definitions.independent_system_characteristics_schema import (
    EntityItemEngineType,
    EntityItemFamilyType,
    EntityItemHashTypeType,
    EntityItemLdaptypeType,
    EntityItemShellType,
    EntityItemVariableRefType,
    EntityItemWindowsViewType,
    Environmentvariable58Item,
    EnvironmentvariableItem,
    FamilyItem,
    Filehash58Item,
    FilehashItem,
    Ldap57Item,
    LdapItem,
    ShellcommandItem,
    Sql57Item,
    Sql512Item,
    SqlItem,
    TextfilecontentItem,
    VariableItem,
    XmlfilecontentItem,
    YamlfilecontentItem,
)
from oval.definitions.linux_definitions_schema import (
    ApparmorstatusObject,
    ApparmorstatusState,
    ApparmorstatusTest,
    DpkginfoObject,
    DpkginfoState,
    DpkginfoTest,
    EntityStateRpmVerifyResultType,
    EntityStateSestatusModeType,
    EntityStateSestatusPolicyType,
    EntityStateSestatusType,
    IflistenersObject,
    IflistenersState,
    IflistenersTest,
    InetlisteningserversObject,
    InetlisteningserversState,
    InetlisteningserversTest,
    KernelmoduleObject,
    KernelmoduleState,
    KernelmoduleTest,
    PartitionObject,
    PartitionState,
    PartitionTest,
    RpmInfoBehaviors,
    RpminfoObject,
    RpminfoState,
    RpminfoTest,
    RpmVerifyBehaviors,
    RpmVerifyFileBehaviors,
    RpmverifyfileObject,
    RpmverifyfileState,
    RpmverifyfileTest,
    RpmverifyObject,
    RpmVerifyPackageBehaviors,
    RpmverifypackageObject,
    RpmverifypackageState,
    RpmverifypackageTest,
    RpmverifyState,
    RpmverifyTest,
    SelinuxbooleanObject,
    SelinuxbooleanState,
    SelinuxbooleanTest,
    SelinuxsecuritycontextObject,
    SelinuxsecuritycontextState,
    SelinuxsecuritycontextTest,
    SestatusObject,
    SestatusState,
    SestatusTest,
    SlackwarepkginfoObject,
    SlackwarepkginfoState,
    SlackwarepkginfoTest,
    SystemdunitdependencyObject,
    SystemdunitdependencyState,
    SystemdunitdependencyTest,
    SystemdunitpropertyObject,
    SystemdunitpropertyState,
    SystemdunitpropertyTest,
)
from oval.definitions.linux_definitions_schema import (
    EntityStateProtocolType as LinuxEntityStateProtocolType,
)
from oval.definitions.linux_definitions_schema import (
    EpochDatatype as EpochDatatype,
)
from oval.definitions.linux_definitions_schema import (
    EvrDatatype as EvrDatatype,
)
from oval.definitions.linux_definitions_schema import (
    FileBehaviors as LinuxFileBehaviors,
)
from oval.definitions.linux_definitions_schema import (
    FileBehaviorsRecurse as LinuxFileBehaviorsRecurse,
)
from oval.definitions.linux_definitions_schema import (
    FileBehaviorsRecurseDirection as LinuxFileBehaviorsRecurseDirection,
)
from oval.definitions.linux_definitions_schema import (
    FileBehaviorsRecurseFileSystem as LinuxFileBehaviorsRecurseFileSystem,
)
from oval.definitions.linux_definitions_schema import (
    ReleaseDatatype as ReleaseDatatype,
)
from oval.definitions.linux_definitions_schema import (
    VersionDatatype as VersionDatatype,
)
from oval.definitions.linux_system_characteristics_schema import (
    ApparmorstatusItem,
    DpkginfoItem,
    EntityItemProtocolType,
    EntityItemRpmVerifyResultType,
    EntityItemSestatusModeType,
    EntityItemSestatusPolicyType,
    EntityItemSestatusType,
    IflistenersItem,
    InetlisteningserverItem,
    KernelmoduleItem,
    PartitionItem,
    RpminfoItem,
    RpmverifyfileItem,
    RpmverifyItem,
    RpmverifypackageItem,
    SelinuxbooleanItem,
    SelinuxsecuritycontextItem,
    SestatusItem,
    SlackwarepkginfoItem,
    SystemdunitdependencyItem,
    SystemdunitpropertyItem,
)
from oval.definitions.linux_system_characteristics_schema import (
    EpochDatatype as SystemCharacteristicsEpochDatatype,
)
from oval.definitions.linux_system_characteristics_schema import (
    EvrDatatype as SystemCharacteristicsEvrDatatype,
)
from oval.definitions.linux_system_characteristics_schema import (
    ReleaseDatatype as SystemCharacteristicsReleaseDatatype,
)
from oval.definitions.linux_system_characteristics_schema import (
    VersionDatatype as SystemCharacteristicsVersionDatatype,
)
from oval.definitions.oval_common_schema import (
    CheckEnumeration,
    ClassEnumeration,
    DatatypeEnumeration,
    DeprecatedInfo,
    DeprecatedInfoType,
    ElementMapItemType,
    ElementMapping,
    ElementMapType,
    ExistenceEnumeration,
    FamilyEnumeration,
    MessageLevelEnumeration,
    OperationEnumeration,
    SchemaVersionType,
    SimpleDatatypeEnumeration,
)
from oval.definitions.oval_common_schema import (
    GeneratorType as CommonSchemaGeneratorType,
)
from oval.definitions.oval_common_schema import (
    MessageType as CommonSchemaMessageType,
)
from oval.definitions.oval_common_schema import (
    Notes as CommonNotes,
)
from oval.definitions.oval_common_schema import (
    NotesType as CommonSchemaNotesType,
)
from oval.definitions.oval_common_schema import (
    OperatorEnumeration as CommonSchemaOperatorEnumeration,
)
from oval.definitions.oval_definitions_schema import (
    AffectedType,
    ArithmeticEnumeration,
    ArithmeticFunctionType,
    BeginFunctionType,
    ConcatFunctionType,
    ConstantVariable,
    CountFunctionType,
    DateTimeFormatEnumeration,
    Definition,
    EndFunctionType,
    EntityComplexBaseType,
    EntityObjectAnySimpleType,
    EntityObjectBinaryType,
    EntityObjectBoolType,
    EntityObjectFieldType,
    EntityObjectFloatType,
    EntityObjectIntType,
    EntityObjectIpaddressStringType,
    EntityObjectIpaddressStringTypeDatatype,
    EntityObjectIpaddressType,
    EntityObjectIpaddressTypeDatatype,
    EntityObjectRecordType,
    EntityObjectStringType,
    EntityObjectVersionType,
    EntitySimpleBaseType,
    EntityStateAnySimpleType,
    EntityStateBinaryType,
    EntityStateBoolType,
    EntityStateComplexBaseType,
    EntityStateDebianEvrstringType,
    EntityStateEvrstringType,
    EntityStateFieldType,
    EntityStateFileSetRevisionType,
    EntityStateFloatType,
    EntityStateIntType,
    EntityStateIosversionType,
    EntityStateIosversionTypeDatatype,
    EntityStateIpaddressStringType,
    EntityStateIpaddressStringTypeDatatype,
    EntityStateIpaddressType,
    EntityStateIpaddressTypeDatatype,
    EntityStateRecordType,
    EntityStateSimpleBaseType,
    EntityStateStringType,
    EntityStateVersionType,
    EscapeRegexFunctionType,
    ExternalVariable,
    Filter,
    FilterActionEnumeration,
    GlobToRegexFunctionType,
    LiteralComponentType,
    LocalVariable,
    MergeFunctionType,
    ObjectComponentType,
    ObjectRefType,
    OrderEnumeration,
    OvalDefinitions,
    PossibleRestrictionType,
    PossibleValueType,
    RegexCaptureFunctionType,
    RestrictionType,
    Set,
    SetOperatorEnumeration,
    SortEnumeration,
    SplitFunctionType,
    State,
    StateRefType,
    StateType,
    SubstringFunctionType,
    Test,
    TimeDifferenceFunctionType,
    UniqueFunctionType,
    Variable,
    VariableComponentType,
)
from oval.definitions.oval_definitions_schema import (
    CriteriaType as CriteriaType,
)
from oval.definitions.oval_definitions_schema import (
    CriterionType as CriterionType,
)
from oval.definitions.oval_definitions_schema import (
    DefinitionsType as DefinitionsType,
)
from oval.definitions.oval_definitions_schema import (
    DefinitionType as DefinitionType,
)
from oval.definitions.oval_definitions_schema import (
    ExtendDefinitionType as ExtendDefinitionType,
)
from oval.definitions.oval_definitions_schema import (
    MetadataType as SchemaMetadataType,
)
from oval.definitions.oval_definitions_schema import (
    Notes as Notes,
)
from oval.definitions.oval_definitions_schema import (
    Object as Object,
)
from oval.definitions.oval_definitions_schema import (
    ObjectType as ObjectType,
)
from oval.definitions.oval_definitions_schema import (
    ReferenceType as ReferenceType,
)
from oval.definitions.oval_definitions_schema import (
    TestType as TestType,
)
from oval.definitions.oval_definitions_schema import (
    ValueType as SchemaValueType,
)
from oval.definitions.oval_definitions_schema import (
    VariablesType as VariablesType,
)
from oval.definitions.oval_definitions_schema import (
    VariableType as VariableType,
)
from oval.definitions.oval_directives_schema import OvalDirectives
from oval.definitions.oval_results_schema import (
    ClassDirectivesType,
    ContentEnumeration,
    DefaultDirectivesType,
    DirectivesType,
    DirectiveType,
    OvalResults,
    ResultEnumeration,
    ResultsType,
    SystemType,
    TestedItemType,
    TestedVariableType,
)
from oval.definitions.oval_results_schema import (
    CriteriaType as ResultsCriteriaType,
)
from oval.definitions.oval_results_schema import (
    CriterionType as ResultsCriterionType,
)
from oval.definitions.oval_results_schema import (
    DefinitionsType as ResultsDefinitionsType,
)
from oval.definitions.oval_results_schema import (
    DefinitionType as ResultsDefinitionType,
)
from oval.definitions.oval_results_schema import (
    ExtendDefinitionType as ResultsExtendDefinitionType,
)
from oval.definitions.oval_results_schema import (
    TestType as ResultsTestType,
)
from oval.definitions.oval_system_characteristics_schema import (
    CollectedObjectsType,
    EntityItemAnySimpleType,
    EntityItemBinaryType,
    EntityItemBoolType,
    EntityItemComplexBaseType,
    EntityItemDebianEvrstringType,
    EntityItemEvrstringType,
    EntityItemFieldType,
    EntityItemFilesetRevisionType,
    EntityItemFloatType,
    EntityItemIntType,
    EntityItemIosversionType,
    EntityItemIpaddressStringType,
    EntityItemIpaddressStringTypeDatatype,
    EntityItemIpaddressType,
    EntityItemIpaddressTypeDatatype,
    EntityItemRecordType,
    EntityItemSimpleBaseType,
    EntityItemStringType,
    EntityItemVersionType,
    FlagEnumeration,
    InterfacesType,
    InterfaceType,
    OvalSystemCharacteristics,
    StatusEnumeration,
    SystemInfoType,
    VariableValueType,
)
from oval.definitions.oval_system_characteristics_schema import (
    Item as SystemCharacteristicsSchemaItem,
)
from oval.definitions.oval_system_characteristics_schema import (
    ItemType as SystemCharacteristicsSchemaItemType,
)
from oval.definitions.oval_system_characteristics_schema import (
    ObjectType as SystemCharacteristicsObjectType,
)
from oval.definitions.oval_system_characteristics_schema import (
    ReferenceType as SystemCharacteristicsReferenceType,
)
from oval.definitions.oval_variables_schema import (
    OvalVariables,
)
from oval.definitions.oval_variables_schema import (
    VariablesType as VariablesVariablesType,
)
from oval.definitions.oval_variables_schema import (
    VariableType as VariablesVariableType,
)
from oval.definitions.scap_source_data_stream_1_3 import (
    Component,
    ComponentRef,
    ContentSourceType,
    DataStream,
    DataStreamCollection,
    ExtendedComponent,
    RefListType,
    ScapVersionType,
    UseCaseType,
)
from oval.definitions.unix_definitions_schema import (
    ATimeDatatype as ATimeDatatype,
)
from oval.definitions.unix_definitions_schema import (
    ChgAllowDatatype as ChgAllowDatatype,
)
from oval.definitions.unix_definitions_schema import (
    ChgLstDatatype as ChgLstDatatype,
)
from oval.definitions.unix_definitions_schema import (
    ChgReqDatatype as ChgReqDatatype,
)
from oval.definitions.unix_definitions_schema import (
    CTimeDatatype as CTimeDatatype,
)
from oval.definitions.unix_definitions_schema import (
    DnscacheObject as UnixDnscacheObject,
)
from oval.definitions.unix_definitions_schema import (
    DnscacheState as UnixDnscacheState,
)
from oval.definitions.unix_definitions_schema import (
    DnscacheTest as UnixDnscacheTest,
)
from oval.definitions.unix_definitions_schema import (
    EntityStateCapabilityType,
    EntityStateEncryptMethodType,
    EntityStateEndpointType,
    EntityStateGconfTypeType,
    EntityStateInterfaceType,
    EntityStateRoutingTableFlagsType,
    EntityStateWaitStatusType,
    EntityStateXinetdTypeStatusType,
    FileextendedattributeObject,
    FileextendedattributeState,
    FileextendedattributeTest,
    GconfObject,
    GconfState,
    GconfTest,
    InetdObject,
    InetdState,
    InetdTest,
    PasswordObject,
    PasswordState,
    PasswordTest,
    RoutingtableObject,
    RoutingtableState,
    RoutingtableTest,
    RunlevelObject,
    RunlevelState,
    RunlevelTest,
    SccsObject,
    SccsState,
    SccsTest,
    ShadowObject,
    ShadowState,
    ShadowTest,
    SshdObject,
    SshdState,
    SshdTest,
    SymlinkObject,
    SymlinkState,
    SymlinkTest,
    SysctlObject,
    SysctlState,
    SysctlTest,
    UnameObject,
    UnameState,
    UnameTest,
    XinetdObject,
    XinetdState,
    XinetdTest,
)
from oval.definitions.unix_definitions_schema import (
    ExpDateDatatype as ExpDateDatatype,
)
from oval.definitions.unix_definitions_schema import (
    ExpInactDatatype as ExpInactDatatype,
)
from oval.definitions.unix_definitions_schema import (
    ExpWarnDatatype as ExpWarnDatatype,
)
from oval.definitions.unix_definitions_schema import (
    FileBehaviors as UnixFileBehaviors,
)
from oval.definitions.unix_definitions_schema import (
    FileBehaviorsRecurse as UnixFileBehaviorsRecurse,
)
from oval.definitions.unix_definitions_schema import (
    FileBehaviorsRecurseDirection as UnixFileBehaviorsRecurseDirection,
)
from oval.definitions.unix_definitions_schema import (
    FileBehaviorsRecurseFileSystem as UnixFileBehaviorsRecurseFileSystem,
)
from oval.definitions.unix_definitions_schema import (
    FileObject as UnixFileObject,
)
from oval.definitions.unix_definitions_schema import (
    FileState as UnixFileState,
)
from oval.definitions.unix_definitions_schema import (
    FileTest as UnixFileTest,
)
from oval.definitions.unix_definitions_schema import (
    FlagDatatype as FlagDatatype,
)
from oval.definitions.unix_definitions_schema import (
    GroupIdDatatype as GroupIdDatatype,
)
from oval.definitions.unix_definitions_schema import (
    InterfaceObject as UnixInterfaceObject,
)
from oval.definitions.unix_definitions_schema import (
    InterfaceState as UnixInterfaceState,
)
from oval.definitions.unix_definitions_schema import (
    InterfaceTest as UnixInterfaceTest,
)
from oval.definitions.unix_definitions_schema import (
    MTimeDatatype as MTimeDatatype,
)
from oval.definitions.unix_definitions_schema import (
    Process58Object as UnixProcess58Object,
)
from oval.definitions.unix_definitions_schema import (
    Process58State as UnixProcess58State,
)
from oval.definitions.unix_definitions_schema import (
    Process58Test as UnixProcess58Test,
)
from oval.definitions.unix_definitions_schema import (
    ProcessObject as UnixProcessObject,
)
from oval.definitions.unix_definitions_schema import (
    ProcessState as UnixProcessState,
)
from oval.definitions.unix_definitions_schema import (
    ProcessTest as UnixProcessTest,
)
from oval.definitions.unix_definitions_schema import (
    UserIdDatatype as UserIdDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ATimeDatatype as SystemCharacteristicsATimeDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ChgAllowDatatype as SystemCharacteristicsChgAllowDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ChgLstDatatype as SystemCharacteristicsChgLstDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ChgReqDatatype as SystemCharacteristicsChgReqDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    CTimeDatatype as SystemCharacteristicsCTimeDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    DnscacheItem,
    EntityItemCapabilityType,
    EntityItemEncryptMethodType,
    EntityItemEndpointType,
    EntityItemGconfTypeType,
    EntityItemInterfaceType,
    EntityItemRoutingTableFlagsType,
    EntityItemWaitStatusType,
    EntityItemXinetdTypeStatusType,
    FileextendedattributeItem,
    FileItem,
    GconfItem,
    InetdItem,
    InterfaceItem,
    PasswordItem,
    Process58Item,
    ProcessItem,
    RoutingtableItem,
    RunlevelItem,
    SccsItem,
    ShadowItem,
    SshdItem,
    SymlinkItem,
    SysctlItem,
    UnameItem,
    XinetdItem,
)
from oval.definitions.unix_system_characteristics_schema import (
    ExpDateDatatype as SystemCharacteristicsExpDateDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ExpInactDatatype as SystemCharacteristicsExpInactDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    ExpWarnDatatype as SystemCharacteristicsExpWarnDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    FlagDatatype as SystemCharacteristicsFlagDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    GroupIdDatatype as SystemCharacteristicsGroupIdDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    MTimeDatatype as SystemCharacteristicsMTimeDatatype,
)
from oval.definitions.unix_system_characteristics_schema import (
    UserIdDatatype as SystemCharacteristicsUserIdDatatype,
)
from oval.definitions.windows_definitions_schema import (
    AccesstokenBehaviors,
    AccesstokenObject,
    AccesstokenState,
    AccesstokenTest,
    Activedirectory57Object,
    Activedirectory57State,
    Activedirectory57Test,
    ActivedirectoryObject,
    ActivedirectoryState,
    ActivedirectoryTest,
    AuditeventpolicyObject,
    AuditeventpolicyState,
    AuditeventpolicysubcategoriesObject,
    AuditeventpolicysubcategoriesState,
    AuditeventpolicysubcategoriesTest,
    AuditeventpolicyTest,
    CmdletObject,
    CmdletState,
    CmdletTest,
    EntityObjectCmdletVerbType,
    EntityObjectGuidtype,
    EntityObjectNamingContextType,
    EntityObjectProtocolType,
    EntityObjectRegistryHiveType,
    EntityObjectSystemMetricIndexType,
    EntityObjectUserRightType,
    EntityStateAddrTypeType,
    EntityStateAdstypeType,
    EntityStateAuditType,
    EntityStateCmdletVerbType,
    EntityStateDriveTypeType,
    EntityStateFileTypeType,
    EntityStateGuidtype,
    EntityStateInterfaceTypeType,
    EntityStateNamingContextType,
    EntityStateNtuserAccountTypeType,
    EntityStatePeSubsystemType,
    EntityStatePeTargetMachineType,
    EntityStateRegistryHiveType,
    EntityStateRegistryTypeType,
    EntityStateServiceControlsAcceptedType,
    EntityStateServiceCurrentStateType,
    EntityStateServiceStartTypeType,
    EntityStateServiceTypeType,
    EntityStateSharedResourceTypeType,
    EntityStateSystemMetricIndexType,
    EntityStateUserRightType,
    Fileauditedpermissions53Object,
    Fileauditedpermissions53State,
    Fileauditedpermissions53Test,
    FileauditedpermissionsObject,
    FileauditedpermissionsState,
    FileauditedpermissionsTest,
    FileAuditPermissions53Behaviors,
    FileAuditPermissionsBehaviors,
    FileEffectiveRights53Behaviors,
    Fileeffectiverights53Object,
    Fileeffectiverights53State,
    Fileeffectiverights53Test,
    FileEffectiveRightsBehaviors,
    FileeffectiverightsObject,
    FileeffectiverightsState,
    FileeffectiverightsTest,
    GroupObject,
    GroupSidObject,
    GroupSidState,
    GroupSidTest,
    GroupState,
    GroupTest,
    LicenseObject,
    LicenseState,
    LicenseTest,
    LockoutpolicyObject,
    LockoutpolicyState,
    LockoutpolicyTest,
    MetabaseObject,
    MetabaseState,
    MetabaseTest,
    NtuserBehaviors,
    NtuserBehaviorsRecurseDirection,
    NtuserBehaviorsWindowsView,
    NtuserObject,
    NtuserState,
    NtuserTest,
    PasswordpolicyObject,
    PasswordpolicyState,
    PasswordpolicyTest,
    PeheaderObject,
    PeheaderState,
    PeheaderTest,
    PortObject,
    PortState,
    PortTest,
    PrinterEffectiveRightsBehaviors,
    PrintereffectiverightsObject,
    PrintereffectiverightsState,
    PrintereffectiverightsTest,
    RegistryBehaviors,
    RegistryBehaviorsRecurseDirection,
    RegistryBehaviorsWindowsView,
    RegistryObject,
    RegistryState,
    RegistryTest,
    Regkeyauditedpermissions53Object,
    Regkeyauditedpermissions53State,
    Regkeyauditedpermissions53Test,
    RegkeyauditedpermissionsObject,
    RegkeyauditedpermissionsState,
    RegkeyauditedpermissionsTest,
    RegkeyAuditPermissions53Behaviors,
    RegkeyAuditPermissionsBehaviors,
    RegkeyEffectiveRights53Behaviors,
    Regkeyeffectiverights53Object,
    Regkeyeffectiverights53State,
    Regkeyeffectiverights53Test,
    RegkeyEffectiveRightsBehaviors,
    RegkeyeffectiverightsObject,
    RegkeyeffectiverightsState,
    RegkeyeffectiverightsTest,
    ServiceeffectiverightsObject,
    ServiceeffectiverightsState,
    ServiceeffectiverightsTest,
    ServiceObject,
    ServiceState,
    ServiceTest,
    SharedResourceAuditedPermissionsBehaviors,
    SharedresourceauditedpermissionsObject,
    SharedresourceauditedpermissionsState,
    SharedresourceauditedpermissionsTest,
    SharedResourceEffectiveRightsBehaviors,
    SharedresourceeffectiverightsObject,
    SharedresourceeffectiverightsState,
    SharedresourceeffectiverightsTest,
    SharedresourceObject,
    SharedresourceState,
    SharedresourceTest,
    SidBehaviors,
    SidObject,
    SidSidBehaviors,
    SidSidObject,
    SidSidState,
    SidSidTest,
    SidState,
    SidTest,
    SystemmetricObject,
    SystemmetricState,
    SystemmetricTest,
    UacObject,
    UacState,
    UacTest,
    UserObject,
    UserrightObject,
    UserrightState,
    UserrightTest,
    UserSid55Object,
    UserSid55State,
    UserSid55Test,
    UserSidObject,
    UserSidState,
    UserSidTest,
    UserState,
    UserTest,
    VolumeObject,
    VolumeState,
    VolumeTest,
    Wmi57Object,
    Wmi57State,
    Wmi57Test,
    WmiObject,
    WmiState,
    WmiTest,
    WuaUpdateSearcherBehaviors,
    WuaupdatesearcherObject,
    WuaupdatesearcherState,
    WuaupdatesearcherTest,
)
from oval.definitions.windows_definitions_schema import (
    DnscacheObject as WindowsDnscacheObject,
)
from oval.definitions.windows_definitions_schema import (
    DnscacheState as WindowsDnscacheState,
)
from oval.definitions.windows_definitions_schema import (
    DnscacheTest as WindowsDnscacheTest,
)
from oval.definitions.windows_definitions_schema import (
    EntityStateProtocolType as WindowsEntityStateProtocolType,
)
from oval.definitions.windows_definitions_schema import (
    EntityStateWindowsViewType as WindowsEntityStateWindowsViewType,
)
from oval.definitions.windows_definitions_schema import (
    FileBehaviors as WindowsFileBehaviors,
)
from oval.definitions.windows_definitions_schema import (
    FileBehaviorsRecurseDirection as WindowsFileBehaviorsRecurseDirection,
)
from oval.definitions.windows_definitions_schema import (
    FileBehaviorsRecurseFileSystem as WindowsFileBehaviorsRecurseFileSystem,
)
from oval.definitions.windows_definitions_schema import (
    FileBehaviorsWindowsView as WindowsFileBehaviorsWindowsView,
)
from oval.definitions.windows_definitions_schema import (
    FileObject as WindowsFileObject,
)
from oval.definitions.windows_definitions_schema import (
    FileState as WindowsFileState,
)
from oval.definitions.windows_definitions_schema import (
    FileTest as WindowsFileTest,
)
from oval.definitions.windows_definitions_schema import (
    InterfaceObject as WindowsInterfaceObject,
)
from oval.definitions.windows_definitions_schema import (
    InterfaceState as WindowsInterfaceState,
)
from oval.definitions.windows_definitions_schema import (
    InterfaceTest as WindowsInterfaceTest,
)
from oval.definitions.windows_definitions_schema import (
    Process58Object as WindowsProcess58Object,
)
from oval.definitions.windows_definitions_schema import (
    Process58State as WindowsProcess58State,
)
from oval.definitions.windows_definitions_schema import (
    Process58Test as WindowsProcess58Test,
)
from oval.definitions.windows_definitions_schema import (
    ProcessObject as WindowsProcessObject,
)
from oval.definitions.windows_definitions_schema import (
    ProcessState as WindowsProcessState,
)
from oval.definitions.windows_definitions_schema import (
    ProcessTest as WindowsProcessTest,
)
from oval.definitions.xccdf_1_2 import (
    Benchmark,
    BenchmarkReferenceType,
    CcOperatorEnumType,
    CheckContentRefType,
    CheckContentType,
    CheckExportType,
    CheckImportType,
    ComplexCheckType,
    ComplexValueType,
    Cpe2IdrefType,
    DcStatusType,
    FactType,
    FixStrategyEnumType,
    FixTextType,
    FixType,
    Group,
    GroupType,
    HtmlTextType,
    HtmlTextWithSubType,
    IdentityType,
    IdentType,
    IdrefListType,
    IdrefType,
    InstanceFixType,
    InstanceResultType,
    InterfaceHintType,
    Model,
    MsgSevEnumType,
    NoticeType,
    OverrideableCpe2IdrefType,
    OverrideType,
    ParamType,
    PlainTextType,
    Profile,
    ProfileNoteType,
    ProfileRefineRuleType,
    ProfileRefineValueType,
    ProfileSelectType,
    ProfileSetComplexValueType,
    ProfileSetValueType,
    ProfileType,
    RatingEnumType,
    ResultEnumType,
    RoleEnumType,
    Rule,
    RuleResultType,
    RuleType,
    ScoreType,
    SelChoicesType,
    SelComplexValueType,
    SelectableItemType,
    SelNumType,
    SelStringType,
    SeverityEnumType,
    Status,
    StatusType,
    SubType,
    SubUseEnumType,
    Tailoring,
    TailoringBenchmarkReferenceType,
    TailoringReferenceType,
    TailoringType,
    TailoringVersionType,
    TargetFactsType,
    TargetIdRefType,
    TestResult,
    TestResultType,
    TextWithSubType,
    UriRefType,
    Value,
    ValueOperatorType,
    ValueTypeType,
    VersionType,
    WarningCategoryEnumType,
    WarningType,
)
from oval.definitions.xccdf_1_2 import (
    CheckType as Xccdf1CheckType,
)
from oval.definitions.xccdf_1_2 import (
    Item as Xccdf12Item,
)
from oval.definitions.xccdf_1_2 import (
    ItemType as Xccdf12ItemType,
)
from oval.definitions.xccdf_1_2 import (
    MessageType as Xccdf12MessageType,
)
from oval.definitions.xccdf_1_2 import (
    MetadataType as Xccdf12MetadataType,
)
from oval.definitions.xccdf_1_2 import (
    ReferenceType as Xccdf12ReferenceType,
)
from oval.definitions.xccdf_1_2 import (
    SignatureType as Xccdf12SignatureType,
)
from oval.definitions.xccdf_1_2 import (
    TextType as Xccdf1TextType,
)
from oval.definitions.xccdf_1_2 import (
    ValueType as Xccdf12ValueType,
)
from oval.definitions.xmldsig_core_schema import (
    CanonicalizationMethod,
    CanonicalizationMethodType,
    DigestMethod,
    DigestMethodType,
    DigestValue,
    DsakeyValue,
    DsakeyValueType,
    KeyInfo,
    KeyInfoType,
    KeyName,
    KeyValue,
    KeyValueType,
    Manifest,
    ManifestType,
    MgmtData,
    Pgpdata,
    PgpdataType,
    Reference,
    RetrievalMethod,
    RetrievalMethodType,
    RsakeyValue,
    RsakeyValueType,
    Signature,
    SignatureMethod,
    SignatureMethodType,
    SignatureProperties,
    SignaturePropertiesType,
    SignatureProperty,
    SignaturePropertyType,
    SignatureValue,
    SignatureValueType,
    SignedInfo,
    SignedInfoType,
    Spkidata,
    SpkidataType,
    Transform,
    Transforms,
    TransformsType,
    TransformType,
    X509Data,
    X509DataType,
    X509IssuerSerialType,
)
from oval.definitions.xmldsig_core_schema import (
    Object as XmldsigCoreObject,
)
from oval.definitions.xmldsig_core_schema import (
    ObjectType as XmldsigCoreObjectType,
)
from oval.definitions.xmldsig_core_schema import (
    ReferenceType as XmldsigCoreReferenceType,
)
from oval.definitions.xmldsig_core_schema import (
    SignatureType as XmldsigCoreSchemaSignatureType,
)

__all__ = [
    "CpeDictionary3CheckType",
    "CpeDictionary23GeneratorType",
    "CpeDictionary23ItemType",
    "ListType",
    "CpeDictionary23NotesType",
    "ReferencesType",
    "DictionaryTextType",
    "CpeItem",
    "CpeList",
    "CpefactRefType",
    "CheckFactRefType",
    "FactRefType",
    "LogicalTestType",
    "PlatformBaseType",
    "PlatformType",
    "LanguageTextType",
    "CheckFactRef",
    "FactRef",
    "LogicalTest",
    "CpeLanguage23OperatorEnumeration",
    "Platform",
    "PlatformConfiguration",
    "PlatformSpecification",
    "PlatformSpecificationType",
    "EvalutationDefinitionIds",
    "EntityObjectEngineType",
    "EntityObjectHashTypeType",
    "EntityObjectShellType",
    "EntityObjectVariableRefType",
    "EntityStateEngineType",
    "EntityStateFamilyType",
    "EntityStateHashTypeType",
    "EntityStateLdaptypeType",
    "EntityStateShellType",
    "EntityStateVariableRefType",
    "IndependentEntityStateWindowsViewType",
    "IndependentFileBehaviors",
    "IndependentFileBehaviorsRecurse",
    "IndependentFileBehaviorsRecurseDirection",
    "IndependentFileBehaviorsRecurseFileSystem",
    "IndependentFileBehaviorsWindowsView",
    "LdapBehaviors",
    "LdapBehaviorsScope",
    "Textfilecontent54Behaviors",
    "Environmentvariable58Object",
    "Environmentvariable58State",
    "Environmentvariable58Test",
    "EnvironmentvariableObject",
    "EnvironmentvariableState",
    "EnvironmentvariableTest",
    "FamilyObject",
    "FamilyState",
    "FamilyTest",
    "Filehash58Object",
    "Filehash58State",
    "Filehash58Test",
    "FilehashObject",
    "FilehashState",
    "FilehashTest",
    "Ldap57Object",
    "Ldap57State",
    "Ldap57Test",
    "LdapObject",
    "LdapState",
    "LdapTest",
    "ShellcommandObject",
    "ShellcommandState",
    "ShellcommandTest",
    "Sql512Object",
    "Sql512State",
    "Sql512Test",
    "Sql57Object",
    "Sql57State",
    "Sql57Test",
    "SqlObject",
    "SqlState",
    "SqlTest",
    "Textfilecontent54Object",
    "Textfilecontent54State",
    "Textfilecontent54Test",
    "TextfilecontentObject",
    "TextfilecontentState",
    "TextfilecontentTest",
    "UnknownTest",
    "VariableObject",
    "VariableState",
    "VariableTest",
    "XmlfilecontentObject",
    "XmlfilecontentState",
    "XmlfilecontentTest",
    "YamlfilecontentObject",
    "YamlfilecontentState",
    "YamlfilecontentTest",
    "EntityItemEngineType",
    "EntityItemFamilyType",
    "EntityItemHashTypeType",
    "EntityItemLdaptypeType",
    "EntityItemShellType",
    "EntityItemVariableRefType",
    "EntityItemWindowsViewType",
    "Environmentvariable58Item",
    "EnvironmentvariableItem",
    "FamilyItem",
    "Filehash58Item",
    "FilehashItem",
    "Ldap57Item",
    "LdapItem",
    "ShellcommandItem",
    "Sql512Item",
    "Sql57Item",
    "SqlItem",
    "TextfilecontentItem",
    "VariableItem",
    "XmlfilecontentItem",
    "YamlfilecontentItem",
    "LinuxEntityStateProtocolType",
    "EntityStateRpmVerifyResultType",
    "EntityStateSestatusModeType",
    "EntityStateSestatusPolicyType",
    "EntityStateSestatusType",
    "LinuxFileBehaviors",
    "LinuxFileBehaviorsRecurse",
    "LinuxFileBehaviorsRecurseDirection",
    "LinuxFileBehaviorsRecurseFileSystem",
    "RpmInfoBehaviors",
    "RpmVerifyBehaviors",
    "RpmVerifyFileBehaviors",
    "RpmVerifyPackageBehaviors",
    "ApparmorstatusObject",
    "ApparmorstatusState",
    "ApparmorstatusTest",
    "DpkginfoObject",
    "DpkginfoState",
    "DpkginfoTest",
    "EpochDatatype",
    "EvrDatatype",
    "IflistenersObject",
    "IflistenersState",
    "IflistenersTest",
    "InetlisteningserversObject",
    "InetlisteningserversState",
    "InetlisteningserversTest",
    "KernelmoduleObject",
    "KernelmoduleState",
    "KernelmoduleTest",
    "PartitionObject",
    "PartitionState",
    "PartitionTest",
    "ReleaseDatatype",
    "RpminfoObject",
    "RpminfoState",
    "RpminfoTest",
    "RpmverifyObject",
    "RpmverifyState",
    "RpmverifyTest",
    "RpmverifyfileObject",
    "RpmverifyfileState",
    "RpmverifyfileTest",
    "RpmverifypackageObject",
    "RpmverifypackageState",
    "RpmverifypackageTest",
    "SelinuxbooleanObject",
    "SelinuxbooleanState",
    "SelinuxbooleanTest",
    "SelinuxsecuritycontextObject",
    "SelinuxsecuritycontextState",
    "SelinuxsecuritycontextTest",
    "SestatusObject",
    "SestatusState",
    "SestatusTest",
    "SlackwarepkginfoObject",
    "SlackwarepkginfoState",
    "SlackwarepkginfoTest",
    "SystemdunitdependencyObject",
    "SystemdunitdependencyState",
    "SystemdunitdependencyTest",
    "SystemdunitpropertyObject",
    "SystemdunitpropertyState",
    "SystemdunitpropertyTest",
    "VersionDatatype",
    "EntityItemProtocolType",
    "EntityItemRpmVerifyResultType",
    "EntityItemSestatusModeType",
    "EntityItemSestatusPolicyType",
    "EntityItemSestatusType",
    "ApparmorstatusItem",
    "DpkginfoItem",
    "SystemCharacteristicsEpochDatatype",
    "SystemCharacteristicsEvrDatatype",
    "IflistenersItem",
    "InetlisteningserverItem",
    "KernelmoduleItem",
    "PartitionItem",
    "SystemCharacteristicsReleaseDatatype",
    "RpminfoItem",
    "RpmverifyItem",
    "RpmverifyfileItem",
    "RpmverifypackageItem",
    "SelinuxbooleanItem",
    "SelinuxsecuritycontextItem",
    "SestatusItem",
    "SlackwarepkginfoItem",
    "SystemdunitdependencyItem",
    "SystemdunitpropertyItem",
    "SystemCharacteristicsVersionDatatype",
    "CheckEnumeration",
    "ClassEnumeration",
    "DatatypeEnumeration",
    "DeprecatedInfoType",
    "ElementMapItemType",
    "ElementMapType",
    "ExistenceEnumeration",
    "FamilyEnumeration",
    "CommonSchemaGeneratorType",
    "MessageLevelEnumeration",
    "CommonSchemaMessageType",
    "CommonSchemaNotesType",
    "OperationEnumeration",
    "CommonSchemaOperatorEnumeration",
    "SchemaVersionType",
    "SimpleDatatypeEnumeration",
    "DeprecatedInfo",
    "ElementMapping",
    "CommonNotes",
    "AffectedType",
    "ArithmeticEnumeration",
    "ArithmeticFunctionType",
    "BeginFunctionType",
    "ConcatFunctionType",
    "CountFunctionType",
    "CriteriaType",
    "CriterionType",
    "DateTimeFormatEnumeration",
    "DefinitionType",
    "EndFunctionType",
    "EntityComplexBaseType",
    "EntityObjectAnySimpleType",
    "EntityObjectBinaryType",
    "EntityObjectBoolType",
    "EntityObjectFieldType",
    "EntityObjectFloatType",
    "EntityObjectIpaddressStringType",
    "EntityObjectIpaddressStringTypeDatatype",
    "EntityObjectIpaddressType",
    "EntityObjectIpaddressTypeDatatype",
    "EntityObjectIntType",
    "EntityObjectRecordType",
    "EntityObjectStringType",
    "EntityObjectVersionType",
    "EntitySimpleBaseType",
    "EntityStateAnySimpleType",
    "EntityStateBinaryType",
    "EntityStateBoolType",
    "EntityStateComplexBaseType",
    "EntityStateDebianEvrstringType",
    "EntityStateEvrstringType",
    "EntityStateFieldType",
    "EntityStateFileSetRevisionType",
    "EntityStateFloatType",
    "EntityStateIosversionType",
    "EntityStateIosversionTypeDatatype",
    "EntityStateIpaddressStringType",
    "EntityStateIpaddressStringTypeDatatype",
    "EntityStateIpaddressType",
    "EntityStateIpaddressTypeDatatype",
    "EntityStateIntType",
    "EntityStateRecordType",
    "EntityStateSimpleBaseType",
    "EntityStateStringType",
    "EntityStateVersionType",
    "EscapeRegexFunctionType",
    "ExtendDefinitionType",
    "FilterActionEnumeration",
    "GlobToRegexFunctionType",
    "LiteralComponentType",
    "MergeFunctionType",
    "SchemaMetadataType",
    "ObjectComponentType",
    "ObjectRefType",
    "ObjectType",
    "OrderEnumeration",
    "PossibleRestrictionType",
    "PossibleValueType",
    "ReferenceType",
    "RegexCaptureFunctionType",
    "RestrictionType",
    "SetOperatorEnumeration",
    "SortEnumeration",
    "SplitFunctionType",
    "StateRefType",
    "StateType",
    "SubstringFunctionType",
    "TestType",
    "TimeDifferenceFunctionType",
    "UniqueFunctionType",
    "SchemaValueType",
    "VariableComponentType",
    "VariableType",
    "ConstantVariable",
    "Definition",
    "ExternalVariable",
    "Filter",
    "LocalVariable",
    "Notes",
    "Object",
    "OvalDefinitions",
    "Set",
    "State",
    "Test",
    "Variable",
    "OvalDirectives",
    "ClassDirectivesType",
    "ContentEnumeration",
    "ResultsCriteriaType",
    "ResultsCriterionType",
    "DefaultDirectivesType",
    "ResultsDefinitionType",
    "ResultsDefinitionsType",
    "DirectiveType",
    "DirectivesType",
    "ResultsExtendDefinitionType",
    "ResultEnumeration",
    "ResultsType",
    "SystemType",
    "ResultsTestType",
    "TestedItemType",
    "TestedVariableType",
    "OvalResults",
    "CollectedObjectsType",
    "EntityItemAnySimpleType",
    "EntityItemBinaryType",
    "EntityItemBoolType",
    "EntityItemComplexBaseType",
    "EntityItemDebianEvrstringType",
    "EntityItemEvrstringType",
    "EntityItemFieldType",
    "EntityItemFilesetRevisionType",
    "EntityItemFloatType",
    "EntityItemIosversionType",
    "EntityItemIpaddressStringType",
    "EntityItemIpaddressStringTypeDatatype",
    "EntityItemIpaddressType",
    "EntityItemIpaddressTypeDatatype",
    "EntityItemIntType",
    "EntityItemRecordType",
    "EntityItemSimpleBaseType",
    "EntityItemStringType",
    "EntityItemVersionType",
    "FlagEnumeration",
    "InterfaceType",
    "InterfacesType",
    "SystemCharacteristicsSchemaItemType",
    "SystemCharacteristicsObjectType",
    "SystemCharacteristicsReferenceType",
    "StatusEnumeration",
    "SystemInfoType",
    "VariableValueType",
    "SystemCharacteristicsSchemaItem",
    "OvalSystemCharacteristics",
    "VariablesVariableType",
    "VariablesVariablesType",
    "OvalVariables",
    "Component",
    "ComponentRef",
    "ContentSourceType",
    "DataStream",
    "DataStreamCollection",
    "ExtendedComponent",
    "RefListType",
    "ScapVersionType",
    "UseCaseType",
    "EntityStateCapabilityType",
    "EntityStateEncryptMethodType",
    "EntityStateEndpointType",
    "EntityStateGconfTypeType",
    "EntityStateInterfaceType",
    "EntityStateRoutingTableFlagsType",
    "EntityStateWaitStatusType",
    "EntityStateXinetdTypeStatusType",
    "UnixFileBehaviors",
    "UnixFileBehaviorsRecurse",
    "UnixFileBehaviorsRecurseDirection",
    "UnixFileBehaviorsRecurseFileSystem",
    "ATimeDatatype",
    "CTimeDatatype",
    "ChgAllowDatatype",
    "ChgLstDatatype",
    "ChgReqDatatype",
    "UnixDnscacheObject",
    "UnixDnscacheState",
    "UnixDnscacheTest",
    "ExpDateDatatype",
    "ExpInactDatatype",
    "ExpWarnDatatype",
    "UnixFileObject",
    "UnixFileState",
    "UnixFileTest",
    "FileextendedattributeObject",
    "FileextendedattributeState",
    "FileextendedattributeTest",
    "FlagDatatype",
    "GconfObject",
    "GconfState",
    "GconfTest",
    "GroupIdDatatype",
    "InetdObject",
    "InetdState",
    "InetdTest",
    "UnixInterfaceObject",
    "UnixInterfaceState",
    "UnixInterfaceTest",
    "MTimeDatatype",
    "PasswordObject",
    "PasswordState",
    "PasswordTest",
    "UnixProcess58Object",
    "UnixProcess58State",
    "UnixProcess58Test",
    "UnixProcessObject",
    "UnixProcessState",
    "UnixProcessTest",
    "RoutingtableObject",
    "RoutingtableState",
    "RoutingtableTest",
    "RunlevelObject",
    "RunlevelState",
    "RunlevelTest",
    "SccsObject",
    "SccsState",
    "SccsTest",
    "ShadowObject",
    "ShadowState",
    "ShadowTest",
    "SshdObject",
    "SshdState",
    "SshdTest",
    "SymlinkObject",
    "SymlinkState",
    "SymlinkTest",
    "SysctlObject",
    "SysctlState",
    "SysctlTest",
    "UnameObject",
    "UnameState",
    "UnameTest",
    "UserIdDatatype",
    "XinetdObject",
    "XinetdState",
    "XinetdTest",
    "EntityItemCapabilityType",
    "EntityItemEncryptMethodType",
    "EntityItemEndpointType",
    "EntityItemGconfTypeType",
    "EntityItemInterfaceType",
    "EntityItemRoutingTableFlagsType",
    "EntityItemWaitStatusType",
    "EntityItemXinetdTypeStatusType",
    "SystemCharacteristicsATimeDatatype",
    "SystemCharacteristicsCTimeDatatype",
    "SystemCharacteristicsChgAllowDatatype",
    "SystemCharacteristicsChgLstDatatype",
    "SystemCharacteristicsChgReqDatatype",
    "DnscacheItem",
    "SystemCharacteristicsExpDateDatatype",
    "SystemCharacteristicsExpInactDatatype",
    "SystemCharacteristicsExpWarnDatatype",
    "FileItem",
    "FileextendedattributeItem",
    "SystemCharacteristicsFlagDatatype",
    "GconfItem",
    "SystemCharacteristicsGroupIdDatatype",
    "InetdItem",
    "InterfaceItem",
    "SystemCharacteristicsMTimeDatatype",
    "PasswordItem",
    "Process58Item",
    "ProcessItem",
    "RoutingtableItem",
    "RunlevelItem",
    "SccsItem",
    "ShadowItem",
    "SshdItem",
    "SymlinkItem",
    "SysctlItem",
    "UnameItem",
    "SystemCharacteristicsUserIdDatatype",
    "XinetdItem",
    "AccesstokenBehaviors",
    "EntityObjectCmdletVerbType",
    "EntityObjectGuidtype",
    "EntityObjectNamingContextType",
    "EntityObjectProtocolType",
    "EntityObjectRegistryHiveType",
    "EntityObjectSystemMetricIndexType",
    "EntityObjectUserRightType",
    "EntityStateAddrTypeType",
    "EntityStateAdstypeType",
    "EntityStateAuditType",
    "EntityStateCmdletVerbType",
    "EntityStateDriveTypeType",
    "EntityStateFileTypeType",
    "EntityStateGuidtype",
    "EntityStateInterfaceTypeType",
    "EntityStateNtuserAccountTypeType",
    "EntityStateNamingContextType",
    "EntityStatePeSubsystemType",
    "EntityStatePeTargetMachineType",
    "WindowsEntityStateProtocolType",
    "EntityStateRegistryHiveType",
    "EntityStateRegistryTypeType",
    "EntityStateServiceControlsAcceptedType",
    "EntityStateServiceCurrentStateType",
    "EntityStateServiceStartTypeType",
    "EntityStateServiceTypeType",
    "EntityStateSharedResourceTypeType",
    "EntityStateSystemMetricIndexType",
    "EntityStateUserRightType",
    "WindowsEntityStateWindowsViewType",
    "FileAuditPermissions53Behaviors",
    "FileAuditPermissionsBehaviors",
    "WindowsFileBehaviors",
    "WindowsFileBehaviorsRecurseDirection",
    "WindowsFileBehaviorsRecurseFileSystem",
    "WindowsFileBehaviorsWindowsView",
    "FileEffectiveRights53Behaviors",
    "FileEffectiveRightsBehaviors",
    "NtuserBehaviors",
    "NtuserBehaviorsRecurseDirection",
    "NtuserBehaviorsWindowsView",
    "PrinterEffectiveRightsBehaviors",
    "RegistryBehaviors",
    "RegistryBehaviorsRecurseDirection",
    "RegistryBehaviorsWindowsView",
    "RegkeyAuditPermissions53Behaviors",
    "RegkeyAuditPermissionsBehaviors",
    "RegkeyEffectiveRights53Behaviors",
    "RegkeyEffectiveRightsBehaviors",
    "SharedResourceAuditedPermissionsBehaviors",
    "SharedResourceEffectiveRightsBehaviors",
    "SidBehaviors",
    "SidSidBehaviors",
    "WuaUpdateSearcherBehaviors",
    "AccesstokenObject",
    "AccesstokenState",
    "AccesstokenTest",
    "Activedirectory57Object",
    "Activedirectory57State",
    "Activedirectory57Test",
    "ActivedirectoryObject",
    "ActivedirectoryState",
    "ActivedirectoryTest",
    "AuditeventpolicyObject",
    "AuditeventpolicyState",
    "AuditeventpolicyTest",
    "AuditeventpolicysubcategoriesObject",
    "AuditeventpolicysubcategoriesState",
    "AuditeventpolicysubcategoriesTest",
    "CmdletObject",
    "CmdletState",
    "CmdletTest",
    "WindowsDnscacheObject",
    "WindowsDnscacheState",
    "WindowsDnscacheTest",
    "WindowsFileObject",
    "WindowsFileState",
    "WindowsFileTest",
    "Fileauditedpermissions53Object",
    "Fileauditedpermissions53State",
    "Fileauditedpermissions53Test",
    "FileauditedpermissionsObject",
    "FileauditedpermissionsState",
    "FileauditedpermissionsTest",
    "Fileeffectiverights53Object",
    "Fileeffectiverights53State",
    "Fileeffectiverights53Test",
    "FileeffectiverightsObject",
    "FileeffectiverightsState",
    "FileeffectiverightsTest",
    "GroupObject",
    "GroupSidObject",
    "GroupSidState",
    "GroupSidTest",
    "GroupState",
    "GroupTest",
    "WindowsInterfaceObject",
    "WindowsInterfaceState",
    "WindowsInterfaceTest",
    "LicenseObject",
    "LicenseState",
    "LicenseTest",
    "LockoutpolicyObject",
    "LockoutpolicyState",
    "LockoutpolicyTest",
    "MetabaseObject",
    "MetabaseState",
    "MetabaseTest",
    "NtuserObject",
    "NtuserState",
    "NtuserTest",
    "PasswordpolicyObject",
    "PasswordpolicyState",
    "PasswordpolicyTest",
    "PeheaderObject",
    "PeheaderState",
    "PeheaderTest",
    "PortObject",
    "PortState",
    "PortTest",
    "PrintereffectiverightsObject",
    "PrintereffectiverightsState",
    "PrintereffectiverightsTest",
    "WindowsProcess58Object",
    "WindowsProcess58State",
    "WindowsProcess58Test",
    "WindowsProcessObject",
    "WindowsProcessState",
    "WindowsProcessTest",
    "RegistryObject",
    "RegistryState",
    "RegistryTest",
    "Regkeyauditedpermissions53Object",
    "Regkeyauditedpermissions53State",
    "Regkeyauditedpermissions53Test",
    "RegkeyauditedpermissionsObject",
    "RegkeyauditedpermissionsState",
    "RegkeyauditedpermissionsTest",
    "Regkeyeffectiverights53Object",
    "Regkeyeffectiverights53State",
    "Regkeyeffectiverights53Test",
    "RegkeyeffectiverightsObject",
    "RegkeyeffectiverightsState",
    "RegkeyeffectiverightsTest",
    "ServiceObject",
    "ServiceState",
    "ServiceTest",
    "ServiceeffectiverightsObject",
    "ServiceeffectiverightsState",
    "ServiceeffectiverightsTest",
    "SharedresourceObject",
    "SharedresourceState",
    "SharedresourceTest",
    "SharedresourceauditedpermissionsObject",
    "SharedresourceauditedpermissionsState",
    "SharedresourceauditedpermissionsTest",
    "SharedresourceeffectiverightsObject",
    "SharedresourceeffectiverightsState",
    "SharedresourceeffectiverightsTest",
    "SidObject",
    "SidSidObject",
    "SidSidState",
    "SidSidTest",
    "SidState",
    "SidTest",
    "SystemmetricObject",
    "SystemmetricState",
    "SystemmetricTest",
    "UacObject",
    "UacState",
    "UacTest",
    "UserObject",
    "UserSid55Object",
    "UserSid55State",
    "UserSid55Test",
    "UserSidObject",
    "UserSidState",
    "UserSidTest",
    "UserState",
    "UserTest",
    "UserrightObject",
    "UserrightState",
    "UserrightTest",
    "VolumeObject",
    "VolumeState",
    "VolumeTest",
    "Wmi57Object",
    "Wmi57State",
    "Wmi57Test",
    "WmiObject",
    "WmiState",
    "WmiTest",
    "WuaupdatesearcherObject",
    "WuaupdatesearcherState",
    "WuaupdatesearcherTest",
    "Benchmark",
    "Cpe2IdrefType",
    "Group",
    "Xccdf12Item",
    "Profile",
    "Rule",
    "Tailoring",
    "TestResult",
    "Value",
    "BenchmarkReferenceType",
    "CcOperatorEnumType",
    "CheckContentRefType",
    "CheckContentType",
    "CheckExportType",
    "CheckImportType",
    "Xccdf1CheckType",
    "ComplexCheckType",
    "ComplexValueType",
    "DcStatusType",
    "FactType",
    "FixStrategyEnumType",
    "FixTextType",
    "FixType",
    "GroupType",
    "HtmlTextType",
    "HtmlTextWithSubType",
    "IdentType",
    "IdentityType",
    "IdrefListType",
    "IdrefType",
    "InstanceFixType",
    "InstanceResultType",
    "InterfaceHintType",
    "Xccdf12ItemType",
    "Xccdf12MessageType",
    "Xccdf12MetadataType",
    "Model",
    "MsgSevEnumType",
    "NoticeType",
    "OverrideType",
    "OverrideableCpe2IdrefType",
    "ParamType",
    "PlainTextType",
    "ProfileNoteType",
    "ProfileRefineRuleType",
    "ProfileRefineValueType",
    "ProfileSelectType",
    "ProfileSetComplexValueType",
    "ProfileSetValueType",
    "ProfileType",
    "RatingEnumType",
    "Xccdf12ReferenceType",
    "ResultEnumType",
    "RoleEnumType",
    "RuleResultType",
    "RuleType",
    "ScoreType",
    "SelChoicesType",
    "SelComplexValueType",
    "SelNumType",
    "SelStringType",
    "SelectableItemType",
    "SeverityEnumType",
    "Xccdf12SignatureType",
    "Status",
    "StatusType",
    "SubType",
    "SubUseEnumType",
    "TailoringBenchmarkReferenceType",
    "TailoringReferenceType",
    "TailoringType",
    "TailoringVersionType",
    "TargetFactsType",
    "TargetIdRefType",
    "TestResultType",
    "Xccdf1TextType",
    "TextWithSubType",
    "UriRefType",
    "ValueOperatorType",
    "Xccdf12ValueType",
    "ValueTypeType",
    "VersionType",
    "WarningCategoryEnumType",
    "WarningType",
    "CanonicalizationMethod",
    "CanonicalizationMethodType",
    "DsakeyValue",
    "DsakeyValueType",
    "DigestMethod",
    "DigestMethodType",
    "DigestValue",
    "KeyInfo",
    "KeyInfoType",
    "KeyName",
    "KeyValue",
    "KeyValueType",
    "Manifest",
    "ManifestType",
    "MgmtData",
    "XmldsigCoreObject",
    "XmldsigCoreObjectType",
    "Pgpdata",
    "PgpdataType",
    "RsakeyValue",
    "RsakeyValueType",
    "Reference",
    "XmldsigCoreReferenceType",
    "RetrievalMethod",
    "RetrievalMethodType",
    "Spkidata",
    "SpkidataType",
    "Signature",
    "SignatureMethod",
    "SignatureMethodType",
    "SignatureProperties",
    "SignaturePropertiesType",
    "SignatureProperty",
    "SignaturePropertyType",
    "XmldsigCoreSchemaSignatureType",
    "SignatureValue",
    "SignatureValueType",
    "SignedInfo",
    "SignedInfoType",
    "Transform",
    "TransformType",
    "Transforms",
    "TransformsType",
    "X509Data",
    "X509DataType",
    "X509IssuerSerialType",
]
