id: audit_config_file_write_protect
title: Ubuntu must be configured so that audit configuration files are not
  write-accessible by unauthorized users.
discussion: Without restricting who can select audited events, unauthorized users
  could block critical event logging, and misconfigured audits could overload logs
  and hinder incident investigation.
references:
  nist:
    800-53r5:
    - AU-12 b
  disa:
    cci:
    - CCI-000171
    srg:
    - SRG-OS-000063-GPOS-00032
    disa_stig:
      ubuntu_2204:
      - UBTU-22-653065
      ubuntu_2404:
      - UBTU-24-900040
enforcement_info:
  enforcement_type: full
  check:
    shell: stat -c '%a' /etc/audit/audit.rules /etc/audit/auditd.conf /etc/audit/rules.d/* | gawk '{mode=strtonum("0"$1); if (and(mode, compl(0640)) != 0) print $1 }' | wc -l"
    standard_output: "0"
  fix:
    shell: chmod -R 640 /etc/audit/audit.rules /etc/audit/auditd.conf /etc/audit/rules.d/*
platforms:
- name: ubuntu_2204
  benchmarks:
  - name: disa_stig
    severity: medium
  enforcement_info:
    enforcement_type: inherit
- name: ubuntu_2404
  benchmarks:
  - name: disa_stig
    severity: medium
  enforcement_info:
    enforcement_type: inherit
tags:
- testing
