from oval.definitions.sources.independent_definitions_schema import (
    EntityObjectEngineType,
    EntityObjectHashTypeType,
    EntityObjectVariableRefType,
    EntityStateEngineType,
    EntityStateFamilyType,
    EntityStateHashTypeType,
    EntityStateLdaptypeType,
    EntityStateVariableRefType,
    EnvironmentvariableObject,
    EnvironmentvariableState,
    EnvironmentvariableTest,
    FilehashObject,
    FilehashState,
    FilehashTest,
    Ldap57Object,
    Ldap57State,
    Ldap57Test,
    LdapBehaviors,
    LdapBehaviorsScope,
    LdapObject,
    LdapState,
    LdapTest,
    Sql57Object,
    Sql57State,
    Sql57Test,
    SqlObject,
    SqlState,
    SqlTest,
    Textfilecontent54Behaviors,
    TextfilecontentObject,
    TextfilecontentState,
    TextfilecontentTest,
    UnknownTest,
    XmlfilecontentState,
)
from oval.definitions.sources.independent_definitions_schema import (
    EntityStateWindowsViewType as IndependentEntityStateWindowsViewType,
)
from oval.definitions.sources.independent_definitions_schema import (
    FileBehaviors as IndependentFileBehaviors,
)
from oval.definitions.sources.independent_definitions_schema import (
    FileBehaviorsRecurse as IndependentFileBehaviorsRecurse,
)
from oval.definitions.sources.independent_definitions_schema import (
    FileBehaviorsRecurseDirection as IndependentFileBehaviorsRecurseDirection,
)
from oval.definitions.sources.independent_definitions_schema import (
    FileBehaviorsRecurseFileSystem as IndependentFileBehaviorsRecurseFileSystem,
)
from oval.definitions.sources.independent_definitions_schema import (
    FileBehaviorsWindowsView as IndependentFileBehaviorsWindowsView,
)
from oval.definitions.sources.linux_definitions_schema import (
    EntityStateProtocolType as LinuxEntityStateProtocolType,
)
from oval.definitions.sources.linux_definitions_schema import (
    EntityStateRpmVerifyResultType,
    IflistenersObject,
    IflistenersState,
    IflistenersTest,
    RpmInfoBehaviors,
    RpmVerifyBehaviors,
    RpmVerifyFileBehaviors,
    RpmverifyObject,
    RpmVerifyPackageBehaviors,
    RpmverifypackageObject,
    RpmverifypackageState,
    RpmverifypackageTest,
    RpmverifyState,
    RpmverifyTest,
    SlackwarepkginfoObject,
    SlackwarepkginfoState,
    SlackwarepkginfoTest,
)
from oval.definitions.sources.linux_definitions_schema import (
    EpochDatatype as EpochDatatype,
)
from oval.definitions.sources.linux_definitions_schema import (
    FileBehaviors as LinuxFileBehaviors,
)
from oval.definitions.sources.linux_definitions_schema import (
    FileBehaviorsRecurse as LinuxFileBehaviorsRecurse,
)
from oval.definitions.sources.linux_definitions_schema import (
    FileBehaviorsRecurseDirection as LinuxFileBehaviorsRecurseDirection,
)
from oval.definitions.sources.linux_definitions_schema import (
    FileBehaviorsRecurseFileSystem as LinuxFileBehaviorsRecurseFileSystem,
)
from oval.definitions.sources.linux_definitions_schema import (
    ReleaseDatatype as ReleaseDatatype,
)
from oval.definitions.sources.linux_definitions_schema import (
    VersionDatatype as VersionDatatype,
)
from oval.definitions.sources.linux_system_characteristics_schema import (
    DpkginfoItem,
    EntityItemProtocolType,
    EntityItemRpmVerifyResultType,
    IflistenersItem,
    InetlisteningserverItem,
    PartitionItem,
    RpminfoItem,
    RpmverifyfileItem,
    RpmverifyItem,
    RpmverifypackageItem,
    SelinuxbooleanItem,
    SelinuxsecuritycontextItem,
    SlackwarepkginfoItem,
)
from oval.definitions.sources.linux_system_characteristics_schema import (
    EpochDatatype as SystemCharacteristicsEpochDatatype,
)
from oval.definitions.sources.linux_system_characteristics_schema import (
    ReleaseDatatype as SystemCharacteristicsReleaseDatatype,
)
from oval.definitions.sources.linux_system_characteristics_schema import (
    VersionDatatype as SystemCharacteristicsVersionDatatype,
)
from oval.definitions.sources.oval_common_schema import (
    CheckEnumeration,
    ClassEnumeration,
    DatatypeEnumeration,
    DeprecatedInfo,
    DeprecatedInfoType,
    ElementMapItemType,
    ElementMapping,
    ElementMapType,
    ExistenceEnumeration,
    FamilyEnumeration,
    GeneratorType,
    MessageLevelEnumeration,
    MessageType,
    Notes,
    NotesType,
    OperationEnumeration,
    OperatorEnumeration,
    SchemaVersionType,
    SimpleDatatypeEnumeration,
)
from oval.definitions.sources.oval_definitions_schema import (
    AffectedType,
    ArithmeticEnumeration,
    ArithmeticFunctionType,
    BeginFunctionType,
    ConcatFunctionType,
    ConstantVariable,
    CountFunctionType,
    DateTimeFormatEnumeration,
    Definition,
    EncapsulatedDefinition,
    EncapsulatedDefinitionType,
    EndFunctionType,
    EntityComplexBaseType,
    EntityObjectAnySimpleType,
    EntityObjectBinaryType,
    EntityObjectBoolType,
    EntityObjectFieldType,
    EntityObjectFloatType,
    EntityObjectIntType,
    EntityObjectIpaddressStringType,
    EntityObjectIpaddressStringTypeDatatype,
    EntityObjectIpaddressType,
    EntityObjectIpaddressTypeDatatype,
    EntityObjectRecordType,
    EntityObjectStringType,
    EntityObjectVersionType,
    EntitySimpleBaseType,
    EntityStateAnySimpleType,
    EntityStateBinaryType,
    EntityStateBoolType,
    EntityStateComplexBaseType,
    EntityStateDebianEvrstringType,
    EntityStateEvrstringType,
    EntityStateFieldType,
    EntityStateFileSetRevisionType,
    EntityStateFloatType,
    EntityStateIntType,
    EntityStateIosversionType,
    EntityStateIosversionTypeDatatype,
    EntityStateIpaddressStringType,
    EntityStateIpaddressStringTypeDatatype,
    EntityStateIpaddressType,
    EntityStateIpaddressTypeDatatype,
    EntityStateRecordType,
    EntityStateSimpleBaseType,
    EntityStateStringType,
    EntityStateVersionType,
    EscapeRegexFunctionType,
    ExternalVariable,
    Filter,
    FilterActionEnumeration,
    GlobToRegexFunctionType,
    LiteralComponentType,
    LocalVariable,
    MergeFunctionType,
    MetadataType,
    ObjectComponentType,
    ObjectRefType,
    ObjectsType,
    OrderEnumeration,
    OvalDefinitions,
    PossibleRestrictionType,
    PossibleValueType,
    RegexCaptureFunctionType,
    RestrictionType,
    Set,
    SetOperatorEnumeration,
    SortEnumeration,
    SplitFunctionType,
    State,
    StateRefType,
    StatesType,
    StateType,
    SubstringFunctionType,
    Test,
    TimeDifferenceFunctionType,
    UniqueFunctionType,
    ValueType,
    Variable,
    VariableComponentType,
)
from oval.definitions.sources.oval_definitions_schema import (
    CriteriaType as CriteriaType,
)
from oval.definitions.sources.oval_definitions_schema import (
    CriterionType as CriterionType,
)
from oval.definitions.sources.oval_definitions_schema import (
    DefinitionsType as DefinitionsType,
)
from oval.definitions.sources.oval_definitions_schema import (
    DefinitionType as DefinitionType,
)
from oval.definitions.sources.oval_definitions_schema import (
    ExtendDefinitionType as ExtendDefinitionType,
)
from oval.definitions.sources.oval_definitions_schema import (
    Object as Object,
)
from oval.definitions.sources.oval_definitions_schema import (
    ObjectType as ObjectType,
)
from oval.definitions.sources.oval_definitions_schema import (
    ReferenceType as ReferenceType,
)
from oval.definitions.sources.oval_definitions_schema import (
    TestsType as TestsType,
)
from oval.definitions.sources.oval_definitions_schema import (
    TestType as TestType,
)
from oval.definitions.sources.oval_definitions_schema import (
    VariablesType as VariablesType,
)
from oval.definitions.sources.oval_definitions_schema import (
    VariableType as VariableType,
)
from oval.definitions.sources.oval_directives_schema import OvalDirectives
from oval.definitions.sources.oval_results_schema import (
    ClassDirectivesType,
    ContentEnumeration,
    DefaultDirectivesType,
    DirectivesType,
    DirectiveType,
    OvalResults,
    ResultEnumeration,
    ResultsType,
    SystemType,
    TestedItemType,
    TestedVariableType,
)
from oval.definitions.sources.oval_results_schema import (
    CriteriaType as ResultsCriteriaType,
)
from oval.definitions.sources.oval_results_schema import (
    CriterionType as ResultsCriterionType,
)
from oval.definitions.sources.oval_results_schema import (
    DefinitionsType as ResultsDefinitionsType,
)
from oval.definitions.sources.oval_results_schema import (
    DefinitionType as ResultsDefinitionType,
)
from oval.definitions.sources.oval_results_schema import (
    ExtendDefinitionType as ResultsExtendDefinitionType,
)
from oval.definitions.sources.oval_results_schema import (
    TestsType as ResultsTestsType,
)
from oval.definitions.sources.oval_results_schema import (
    TestType as ResultsTestType,
)
from oval.definitions.sources.oval_system_characteristics_schema import (
    CollectedObjectsType,
    EntityItemAnySimpleType,
    EntityItemBinaryType,
    EntityItemBoolType,
    EntityItemComplexBaseType,
    EntityItemDebianEvrstringType,
    EntityItemEvrstringType,
    EntityItemFieldType,
    EntityItemFilesetRevisionType,
    EntityItemFloatType,
    EntityItemIntType,
    EntityItemIosversionType,
    EntityItemIpaddressStringType,
    EntityItemIpaddressStringTypeDatatype,
    EntityItemIpaddressType,
    EntityItemIpaddressTypeDatatype,
    EntityItemRecordType,
    EntityItemSimpleBaseType,
    EntityItemStringType,
    EntityItemVersionType,
    FlagEnumeration,
    InterfacesType,
    InterfaceType,
    Item,
    ItemType,
    OvalSystemCharacteristics,
    StatusEnumeration,
    SystemDataType,
    SystemInfoType,
    VariableValueType,
)
from oval.definitions.sources.oval_system_characteristics_schema import (
    ObjectType as SystemCharacteristicsObjectType,
)
from oval.definitions.sources.oval_system_characteristics_schema import (
    ReferenceType as SystemCharacteristicsReferenceType,
)
from oval.definitions.sources.oval_variables_schema import (
    OvalVariables,
)
from oval.definitions.sources.oval_variables_schema import (
    VariablesType as VariablesVariablesType,
)
from oval.definitions.sources.oval_variables_schema import (
    VariableType as VariablesVariableType,
)
from oval.definitions.sources.unix_definitions_schema import (
    DnscacheObject as UnixDnscacheObject,
)
from oval.definitions.sources.unix_definitions_schema import (
    DnscacheState as UnixDnscacheState,
)
from oval.definitions.sources.unix_definitions_schema import (
    DnscacheTest as UnixDnscacheTest,
)
from oval.definitions.sources.unix_definitions_schema import (
    EntityStateCapabilityType,
    EntityStateEncryptMethodType,
    EntityStateEndpointType,
    EntityStateGconfTypeType,
    EntityStateInterfaceType,
    EntityStateRoutingTableFlagsType,
    EntityStateWaitStatusType,
    EntityStateXinetdTypeStatusType,
    FileextendedattributeObject,
    FileextendedattributeState,
    FileextendedattributeTest,
    GconfObject,
    GconfState,
    GconfTest,
    InetdObject,
    InetdState,
    InetdTest,
    RoutingtableObject,
    RoutingtableState,
    RoutingtableTest,
    RunlevelObject,
    RunlevelState,
    RunlevelTest,
    SccsObject,
    SccsState,
    SccsTest,
    XinetdObject,
    XinetdState,
    XinetdTest,
)
from oval.definitions.sources.unix_definitions_schema import (
    FileBehaviors as UnixFileBehaviors,
)
from oval.definitions.sources.unix_definitions_schema import (
    FileBehaviorsRecurse as UnixFileBehaviorsRecurse,
)
from oval.definitions.sources.unix_definitions_schema import (
    FileBehaviorsRecurseDirection as UnixFileBehaviorsRecurseDirection,
)
from oval.definitions.sources.unix_definitions_schema import (
    FileBehaviorsRecurseFileSystem as UnixFileBehaviorsRecurseFileSystem,
)
from oval.definitions.sources.unix_definitions_schema import (
    Process58State as UnixProcess58State,
)
from oval.definitions.sources.unix_definitions_schema import (
    ProcessObject as UnixProcessObject,
)
from oval.definitions.sources.unix_definitions_schema import (
    ProcessState as UnixProcessState,
)
from oval.definitions.sources.unix_definitions_schema import (
    ProcessTest as UnixProcessTest,
)
from oval.definitions.sources.unix_system_characteristics_schema import (
    DnscacheItem,
    EntityItemCapabilityType,
    EntityItemEncryptMethodType,
    EntityItemEndpointType,
    EntityItemGconfTypeType,
    EntityItemInterfaceType,
    EntityItemRoutingTableFlagsType,
    EntityItemWaitStatusType,
    EntityItemXinetdTypeStatusType,
    FileextendedattributeItem,
    FileItem,
    GconfItem,
    InetdItem,
    InterfaceItem,
    PasswordItem,
    Process58Item,
    ProcessItem,
    RoutingtableItem,
    RunlevelItem,
    SccsItem,
    ShadowItem,
    SysctlItem,
    UnameItem,
    XinetdItem,
)
from oval.definitions.sources.windows_definitions_schema import (
    AccesstokenBehaviors,
    AccesstokenObject,
    AccesstokenState,
    AccesstokenTest,
    Activedirectory57Object,
    Activedirectory57State,
    Activedirectory57Test,
    ActivedirectoryObject,
    ActivedirectoryState,
    ActivedirectoryTest,
    AuditeventpolicyObject,
    AuditeventpolicyState,
    AuditeventpolicysubcategoriesObject,
    AuditeventpolicysubcategoriesState,
    AuditeventpolicysubcategoriesTest,
    AuditeventpolicyTest,
    CmdletObject,
    CmdletState,
    CmdletTest,
    EntityObjectCmdletVerbType,
    EntityObjectGuidtype,
    EntityObjectNamingContextType,
    EntityObjectProtocolType,
    EntityObjectRegistryHiveType,
    EntityObjectSystemMetricIndexType,
    EntityObjectUserRightType,
    EntityStateAddrTypeType,
    EntityStateAdstypeType,
    EntityStateAuditType,
    EntityStateCmdletVerbType,
    EntityStateDriveTypeType,
    EntityStateFileTypeType,
    EntityStateGuidtype,
    EntityStateInterfaceTypeType,
    EntityStateNamingContextType,
    EntityStateNtuserAccountTypeType,
    EntityStatePeSubsystemType,
    EntityStatePeTargetMachineType,
    EntityStateRegistryHiveType,
    EntityStateRegistryTypeType,
    EntityStateServiceControlsAcceptedType,
    EntityStateServiceCurrentStateType,
    EntityStateServiceStartTypeType,
    EntityStateServiceTypeType,
    EntityStateSharedResourceTypeType,
    EntityStateSystemMetricIndexType,
    EntityStateUserRightType,
    Fileauditedpermissions53Object,
    Fileauditedpermissions53State,
    Fileauditedpermissions53Test,
    FileauditedpermissionsObject,
    FileauditedpermissionsState,
    FileauditedpermissionsTest,
    FileAuditPermissions53Behaviors,
    FileAuditPermissionsBehaviors,
    FileEffectiveRights53Behaviors,
    Fileeffectiverights53Object,
    Fileeffectiverights53State,
    Fileeffectiverights53Test,
    FileEffectiveRightsBehaviors,
    FileeffectiverightsObject,
    FileeffectiverightsState,
    FileeffectiverightsTest,
    FileObject,
    FileState,
    FileTest,
    GroupObject,
    GroupSidObject,
    GroupSidState,
    GroupSidTest,
    GroupState,
    GroupTest,
    InterfaceObject,
    InterfaceState,
    InterfaceTest,
    LicenseObject,
    LicenseState,
    LicenseTest,
    LockoutpolicyObject,
    LockoutpolicyState,
    LockoutpolicyTest,
    MetabaseObject,
    MetabaseState,
    MetabaseTest,
    NtuserBehaviors,
    NtuserBehaviorsRecurseDirection,
    NtuserBehaviorsWindowsView,
    NtuserObject,
    NtuserState,
    NtuserTest,
    PasswordpolicyObject,
    PasswordpolicyState,
    PasswordpolicyTest,
    PeheaderObject,
    PeheaderState,
    PeheaderTest,
    PortObject,
    PortState,
    PortTest,
    PrinterEffectiveRightsBehaviors,
    PrintereffectiverightsObject,
    PrintereffectiverightsState,
    PrintereffectiverightsTest,
    Process58Object,
    Process58Test,
    RegistryBehaviors,
    RegistryBehaviorsRecurseDirection,
    RegistryBehaviorsWindowsView,
    RegistryObject,
    RegistryState,
    RegistryTest,
    Regkeyauditedpermissions53Object,
    Regkeyauditedpermissions53State,
    Regkeyauditedpermissions53Test,
    RegkeyauditedpermissionsObject,
    RegkeyauditedpermissionsState,
    RegkeyauditedpermissionsTest,
    RegkeyAuditPermissions53Behaviors,
    RegkeyAuditPermissionsBehaviors,
    RegkeyEffectiveRights53Behaviors,
    Regkeyeffectiverights53Object,
    Regkeyeffectiverights53State,
    Regkeyeffectiverights53Test,
    RegkeyEffectiveRightsBehaviors,
    RegkeyeffectiverightsObject,
    RegkeyeffectiverightsState,
    RegkeyeffectiverightsTest,
    ServiceeffectiverightsObject,
    ServiceeffectiverightsState,
    ServiceeffectiverightsTest,
    ServiceObject,
    ServiceState,
    ServiceTest,
    SharedResourceAuditedPermissionsBehaviors,
    SharedresourceauditedpermissionsObject,
    SharedresourceauditedpermissionsState,
    SharedresourceauditedpermissionsTest,
    SharedResourceEffectiveRightsBehaviors,
    SharedresourceeffectiverightsObject,
    SharedresourceeffectiverightsState,
    SharedresourceeffectiverightsTest,
    SharedresourceObject,
    SharedresourceState,
    SharedresourceTest,
    SidBehaviors,
    SidObject,
    SidSidBehaviors,
    SidSidObject,
    SidSidState,
    SidSidTest,
    SidState,
    SidTest,
    SystemmetricObject,
    SystemmetricState,
    SystemmetricTest,
    UacObject,
    UacState,
    UacTest,
    UserObject,
    UserrightObject,
    UserrightState,
    UserrightTest,
    UserSid55Object,
    UserSid55State,
    UserSid55Test,
    UserSidObject,
    UserSidState,
    UserSidTest,
    UserState,
    UserTest,
    VolumeObject,
    VolumeState,
    VolumeTest,
    Wmi57Object,
    Wmi57State,
    Wmi57Test,
    WmiObject,
    WmiState,
    WmiTest,
    WuaUpdateSearcherBehaviors,
    WuaupdatesearcherObject,
    WuaupdatesearcherState,
    WuaupdatesearcherTest,
)
from oval.definitions.sources.windows_definitions_schema import (
    DnscacheObject as WindowsDnscacheObject,
)
from oval.definitions.sources.windows_definitions_schema import (
    DnscacheState as WindowsDnscacheState,
)
from oval.definitions.sources.windows_definitions_schema import (
    DnscacheTest as WindowsDnscacheTest,
)
from oval.definitions.sources.windows_definitions_schema import (
    EntityStateProtocolType as WindowsEntityStateProtocolType,
)
from oval.definitions.sources.windows_definitions_schema import (
    EntityStateWindowsViewType as WindowsEntityStateWindowsViewType,
)
from oval.definitions.sources.windows_definitions_schema import (
    FileBehaviors as WindowsFileBehaviors,
)
from oval.definitions.sources.windows_definitions_schema import (
    FileBehaviorsRecurseDirection as WindowsFileBehaviorsRecurseDirection,
)
from oval.definitions.sources.windows_definitions_schema import (
    FileBehaviorsRecurseFileSystem as WindowsFileBehaviorsRecurseFileSystem,
)
from oval.definitions.sources.windows_definitions_schema import (
    FileBehaviorsWindowsView as WindowsFileBehaviorsWindowsView,
)
from oval.definitions.sources.windows_definitions_schema import (
    Process58State as WindowsProcess58State,
)
from oval.definitions.sources.windows_definitions_schema import (
    ProcessObject as WindowsProcessObject,
)
from oval.definitions.sources.windows_definitions_schema import (
    ProcessState as WindowsProcessState,
)
from oval.definitions.sources.windows_definitions_schema import (
    ProcessTest as WindowsProcessTest,
)
from oval.definitions.sources.xmldsig_core_schema import (
    CanonicalizationMethod,
    CanonicalizationMethodType,
    DigestMethod,
    DigestMethodType,
    DigestValue,
    DsakeyValue,
    DsakeyValueType,
    KeyInfo,
    KeyInfoType,
    KeyName,
    KeyValue,
    KeyValueType,
    Manifest,
    ManifestType,
    MgmtData,
    Pgpdata,
    PgpdataType,
    Reference,
    RetrievalMethod,
    RetrievalMethodType,
    RsakeyValue,
    RsakeyValueType,
    Signature,
    SignatureMethod,
    SignatureMethodType,
    SignatureProperties,
    SignaturePropertiesType,
    SignatureProperty,
    SignaturePropertyType,
    SignatureType,
    SignatureValue,
    SignatureValueType,
    SignedInfo,
    SignedInfoType,
    Spkidata,
    SpkidataType,
    Transform,
    Transforms,
    TransformsType,
    TransformType,
    X509Data,
    X509DataType,
    X509IssuerSerialType,
)
from oval.definitions.sources.xmldsig_core_schema import (
    Object as XmldsigCoreObject,
)
from oval.definitions.sources.xmldsig_core_schema import (
    ObjectType as XmldsigCoreObjectType,
)
from oval.definitions.sources.xmldsig_core_schema import (
    ReferenceType as XmldsigCoreReferenceType,
)

__all__ = [
    "EntityObjectEngineType",
    "EntityObjectHashTypeType",
    "EntityObjectVariableRefType",
    "EntityStateEngineType",
    "EntityStateFamilyType",
    "EntityStateHashTypeType",
    "EntityStateLdaptypeType",
    "EntityStateVariableRefType",
    "IndependentEntityStateWindowsViewType",
    "IndependentFileBehaviors",
    "IndependentFileBehaviorsRecurse",
    "IndependentFileBehaviorsRecurseDirection",
    "IndependentFileBehaviorsRecurseFileSystem",
    "IndependentFileBehaviorsWindowsView",
    "LdapBehaviors",
    "LdapBehaviorsScope",
    "Textfilecontent54Behaviors",
    "EnvironmentvariableObject",
    "EnvironmentvariableState",
    "EnvironmentvariableTest",
    "FilehashObject",
    "FilehashState",
    "FilehashTest",
    "Ldap57Object",
    "Ldap57State",
    "Ldap57Test",
    "LdapObject",
    "LdapState",
    "LdapTest",
    "Sql57Object",
    "Sql57State",
    "Sql57Test",
    "SqlObject",
    "SqlState",
    "SqlTest",
    "TextfilecontentObject",
    "TextfilecontentState",
    "TextfilecontentTest",
    "UnknownTest",
    "XmlfilecontentState",
    "LinuxEntityStateProtocolType",
    "EntityStateRpmVerifyResultType",
    "LinuxFileBehaviors",
    "LinuxFileBehaviorsRecurse",
    "LinuxFileBehaviorsRecurseDirection",
    "LinuxFileBehaviorsRecurseFileSystem",
    "RpmInfoBehaviors",
    "RpmVerifyBehaviors",
    "RpmVerifyFileBehaviors",
    "RpmVerifyPackageBehaviors",
    "EpochDatatype",
    "IflistenersObject",
    "IflistenersState",
    "IflistenersTest",
    "ReleaseDatatype",
    "RpmverifyObject",
    "RpmverifyState",
    "RpmverifyTest",
    "RpmverifypackageObject",
    "RpmverifypackageState",
    "RpmverifypackageTest",
    "SlackwarepkginfoObject",
    "SlackwarepkginfoState",
    "SlackwarepkginfoTest",
    "VersionDatatype",
    "EntityItemProtocolType",
    "EntityItemRpmVerifyResultType",
    "DpkginfoItem",
    "SystemCharacteristicsEpochDatatype",
    "IflistenersItem",
    "InetlisteningserverItem",
    "PartitionItem",
    "SystemCharacteristicsReleaseDatatype",
    "RpminfoItem",
    "RpmverifyItem",
    "RpmverifyfileItem",
    "RpmverifypackageItem",
    "SelinuxbooleanItem",
    "SelinuxsecuritycontextItem",
    "SlackwarepkginfoItem",
    "SystemCharacteristicsVersionDatatype",
    "CheckEnumeration",
    "ClassEnumeration",
    "DatatypeEnumeration",
    "DeprecatedInfoType",
    "ElementMapItemType",
    "ElementMapType",
    "ExistenceEnumeration",
    "FamilyEnumeration",
    "GeneratorType",
    "MessageLevelEnumeration",
    "MessageType",
    "NotesType",
    "OperationEnumeration",
    "OperatorEnumeration",
    "SchemaVersionType",
    "SimpleDatatypeEnumeration",
    "DeprecatedInfo",
    "ElementMapping",
    "Notes",
    "AffectedType",
    "ArithmeticEnumeration",
    "ArithmeticFunctionType",
    "BeginFunctionType",
    "ConcatFunctionType",
    "CountFunctionType",
    "CriteriaType",
    "CriterionType",
    "DateTimeFormatEnumeration",
    "DefinitionType",
    "DefinitionsType",
    "EncapsulatedDefinitionType",
    "EndFunctionType",
    "EntityComplexBaseType",
    "EntityObjectAnySimpleType",
    "EntityObjectBinaryType",
    "EntityObjectBoolType",
    "EntityObjectFieldType",
    "EntityObjectFloatType",
    "EntityObjectIpaddressStringType",
    "EntityObjectIpaddressStringTypeDatatype",
    "EntityObjectIpaddressType",
    "EntityObjectIpaddressTypeDatatype",
    "EntityObjectIntType",
    "EntityObjectRecordType",
    "EntityObjectStringType",
    "EntityObjectVersionType",
    "EntitySimpleBaseType",
    "EntityStateAnySimpleType",
    "EntityStateBinaryType",
    "EntityStateBoolType",
    "EntityStateComplexBaseType",
    "EntityStateDebianEvrstringType",
    "EntityStateEvrstringType",
    "EntityStateFieldType",
    "EntityStateFileSetRevisionType",
    "EntityStateFloatType",
    "EntityStateIosversionType",
    "EntityStateIosversionTypeDatatype",
    "EntityStateIpaddressStringType",
    "EntityStateIpaddressStringTypeDatatype",
    "EntityStateIpaddressType",
    "EntityStateIpaddressTypeDatatype",
    "EntityStateIntType",
    "EntityStateRecordType",
    "EntityStateSimpleBaseType",
    "EntityStateStringType",
    "EntityStateVersionType",
    "EscapeRegexFunctionType",
    "ExtendDefinitionType",
    "FilterActionEnumeration",
    "GlobToRegexFunctionType",
    "LiteralComponentType",
    "MergeFunctionType",
    "MetadataType",
    "ObjectComponentType",
    "ObjectRefType",
    "ObjectType",
    "ObjectsType",
    "OrderEnumeration",
    "PossibleRestrictionType",
    "PossibleValueType",
    "ReferenceType",
    "RegexCaptureFunctionType",
    "RestrictionType",
    "SetOperatorEnumeration",
    "SortEnumeration",
    "SplitFunctionType",
    "StateRefType",
    "StateType",
    "StatesType",
    "SubstringFunctionType",
    "TestType",
    "TestsType",
    "TimeDifferenceFunctionType",
    "UniqueFunctionType",
    "ValueType",
    "VariableComponentType",
    "VariableType",
    "VariablesType",
    "ConstantVariable",
    "Definition",
    "EncapsulatedDefinition",
    "ExternalVariable",
    "Filter",
    "LocalVariable",
    "Object",
    "OvalDefinitions",
    "Set",
    "State",
    "Test",
    "Variable",
    "OvalDirectives",
    "ClassDirectivesType",
    "ContentEnumeration",
    "ResultsCriteriaType",
    "ResultsCriterionType",
    "DefaultDirectivesType",
    "ResultsDefinitionType",
    "ResultsDefinitionsType",
    "DirectiveType",
    "DirectivesType",
    "ResultsExtendDefinitionType",
    "ResultEnumeration",
    "ResultsType",
    "SystemType",
    "ResultsTestType",
    "TestedItemType",
    "TestedVariableType",
    "ResultsTestsType",
    "OvalResults",
    "CollectedObjectsType",
    "EntityItemAnySimpleType",
    "EntityItemBinaryType",
    "EntityItemBoolType",
    "EntityItemComplexBaseType",
    "EntityItemDebianEvrstringType",
    "EntityItemEvrstringType",
    "EntityItemFieldType",
    "EntityItemFilesetRevisionType",
    "EntityItemFloatType",
    "EntityItemIosversionType",
    "EntityItemIpaddressStringType",
    "EntityItemIpaddressStringTypeDatatype",
    "EntityItemIpaddressType",
    "EntityItemIpaddressTypeDatatype",
    "EntityItemIntType",
    "EntityItemRecordType",
    "EntityItemSimpleBaseType",
    "EntityItemStringType",
    "EntityItemVersionType",
    "FlagEnumeration",
    "InterfaceType",
    "InterfacesType",
    "ItemType",
    "SystemCharacteristicsObjectType",
    "SystemCharacteristicsReferenceType",
    "StatusEnumeration",
    "SystemDataType",
    "SystemInfoType",
    "VariableValueType",
    "Item",
    "OvalSystemCharacteristics",
    "VariablesVariableType",
    "VariablesVariablesType",
    "OvalVariables",
    "EntityStateCapabilityType",
    "EntityStateEncryptMethodType",
    "EntityStateEndpointType",
    "EntityStateGconfTypeType",
    "EntityStateInterfaceType",
    "EntityStateRoutingTableFlagsType",
    "EntityStateWaitStatusType",
    "EntityStateXinetdTypeStatusType",
    "UnixFileBehaviors",
    "UnixFileBehaviorsRecurse",
    "UnixFileBehaviorsRecurseDirection",
    "UnixFileBehaviorsRecurseFileSystem",
    "UnixDnscacheObject",
    "UnixDnscacheState",
    "UnixDnscacheTest",
    "FileextendedattributeObject",
    "FileextendedattributeState",
    "FileextendedattributeTest",
    "GconfObject",
    "GconfState",
    "GconfTest",
    "InetdObject",
    "InetdState",
    "InetdTest",
    "UnixProcess58State",
    "UnixProcessObject",
    "UnixProcessState",
    "UnixProcessTest",
    "RoutingtableObject",
    "RoutingtableState",
    "RoutingtableTest",
    "RunlevelObject",
    "RunlevelState",
    "RunlevelTest",
    "SccsObject",
    "SccsState",
    "SccsTest",
    "XinetdObject",
    "XinetdState",
    "XinetdTest",
    "EntityItemCapabilityType",
    "EntityItemEncryptMethodType",
    "EntityItemEndpointType",
    "EntityItemGconfTypeType",
    "EntityItemInterfaceType",
    "EntityItemRoutingTableFlagsType",
    "EntityItemWaitStatusType",
    "EntityItemXinetdTypeStatusType",
    "DnscacheItem",
    "FileItem",
    "FileextendedattributeItem",
    "GconfItem",
    "InetdItem",
    "InterfaceItem",
    "PasswordItem",
    "Process58Item",
    "ProcessItem",
    "RoutingtableItem",
    "RunlevelItem",
    "SccsItem",
    "ShadowItem",
    "SysctlItem",
    "UnameItem",
    "XinetdItem",
    "AccesstokenBehaviors",
    "EntityObjectCmdletVerbType",
    "EntityObjectGuidtype",
    "EntityObjectNamingContextType",
    "EntityObjectProtocolType",
    "EntityObjectRegistryHiveType",
    "EntityObjectSystemMetricIndexType",
    "EntityObjectUserRightType",
    "EntityStateAddrTypeType",
    "EntityStateAdstypeType",
    "EntityStateAuditType",
    "EntityStateCmdletVerbType",
    "EntityStateDriveTypeType",
    "EntityStateFileTypeType",
    "EntityStateGuidtype",
    "EntityStateInterfaceTypeType",
    "EntityStateNtuserAccountTypeType",
    "EntityStateNamingContextType",
    "EntityStatePeSubsystemType",
    "EntityStatePeTargetMachineType",
    "WindowsEntityStateProtocolType",
    "EntityStateRegistryHiveType",
    "EntityStateRegistryTypeType",
    "EntityStateServiceControlsAcceptedType",
    "EntityStateServiceCurrentStateType",
    "EntityStateServiceStartTypeType",
    "EntityStateServiceTypeType",
    "EntityStateSharedResourceTypeType",
    "EntityStateSystemMetricIndexType",
    "EntityStateUserRightType",
    "WindowsEntityStateWindowsViewType",
    "FileAuditPermissions53Behaviors",
    "FileAuditPermissionsBehaviors",
    "WindowsFileBehaviors",
    "WindowsFileBehaviorsRecurseDirection",
    "WindowsFileBehaviorsRecurseFileSystem",
    "WindowsFileBehaviorsWindowsView",
    "FileEffectiveRights53Behaviors",
    "FileEffectiveRightsBehaviors",
    "NtuserBehaviors",
    "NtuserBehaviorsRecurseDirection",
    "NtuserBehaviorsWindowsView",
    "PrinterEffectiveRightsBehaviors",
    "RegistryBehaviors",
    "RegistryBehaviorsRecurseDirection",
    "RegistryBehaviorsWindowsView",
    "RegkeyAuditPermissions53Behaviors",
    "RegkeyAuditPermissionsBehaviors",
    "RegkeyEffectiveRights53Behaviors",
    "RegkeyEffectiveRightsBehaviors",
    "SharedResourceAuditedPermissionsBehaviors",
    "SharedResourceEffectiveRightsBehaviors",
    "SidBehaviors",
    "SidSidBehaviors",
    "WuaUpdateSearcherBehaviors",
    "AccesstokenObject",
    "AccesstokenState",
    "AccesstokenTest",
    "Activedirectory57Object",
    "Activedirectory57State",
    "Activedirectory57Test",
    "ActivedirectoryObject",
    "ActivedirectoryState",
    "ActivedirectoryTest",
    "AuditeventpolicyObject",
    "AuditeventpolicyState",
    "AuditeventpolicyTest",
    "AuditeventpolicysubcategoriesObject",
    "AuditeventpolicysubcategoriesState",
    "AuditeventpolicysubcategoriesTest",
    "CmdletObject",
    "CmdletState",
    "CmdletTest",
    "WindowsDnscacheObject",
    "WindowsDnscacheState",
    "WindowsDnscacheTest",
    "FileObject",
    "FileState",
    "FileTest",
    "Fileauditedpermissions53Object",
    "Fileauditedpermissions53State",
    "Fileauditedpermissions53Test",
    "FileauditedpermissionsObject",
    "FileauditedpermissionsState",
    "FileauditedpermissionsTest",
    "Fileeffectiverights53Object",
    "Fileeffectiverights53State",
    "Fileeffectiverights53Test",
    "FileeffectiverightsObject",
    "FileeffectiverightsState",
    "FileeffectiverightsTest",
    "GroupObject",
    "GroupSidObject",
    "GroupSidState",
    "GroupSidTest",
    "GroupState",
    "GroupTest",
    "InterfaceObject",
    "InterfaceState",
    "InterfaceTest",
    "LicenseObject",
    "LicenseState",
    "LicenseTest",
    "LockoutpolicyObject",
    "LockoutpolicyState",
    "LockoutpolicyTest",
    "MetabaseObject",
    "MetabaseState",
    "MetabaseTest",
    "NtuserObject",
    "NtuserState",
    "NtuserTest",
    "PasswordpolicyObject",
    "PasswordpolicyState",
    "PasswordpolicyTest",
    "PeheaderObject",
    "PeheaderState",
    "PeheaderTest",
    "PortObject",
    "PortState",
    "PortTest",
    "PrintereffectiverightsObject",
    "PrintereffectiverightsState",
    "PrintereffectiverightsTest",
    "Process58Object",
    "WindowsProcess58State",
    "Process58Test",
    "WindowsProcessObject",
    "WindowsProcessState",
    "WindowsProcessTest",
    "RegistryObject",
    "RegistryState",
    "RegistryTest",
    "Regkeyauditedpermissions53Object",
    "Regkeyauditedpermissions53State",
    "Regkeyauditedpermissions53Test",
    "RegkeyauditedpermissionsObject",
    "RegkeyauditedpermissionsState",
    "RegkeyauditedpermissionsTest",
    "Regkeyeffectiverights53Object",
    "Regkeyeffectiverights53State",
    "Regkeyeffectiverights53Test",
    "RegkeyeffectiverightsObject",
    "RegkeyeffectiverightsState",
    "RegkeyeffectiverightsTest",
    "ServiceObject",
    "ServiceState",
    "ServiceTest",
    "ServiceeffectiverightsObject",
    "ServiceeffectiverightsState",
    "ServiceeffectiverightsTest",
    "SharedresourceObject",
    "SharedresourceState",
    "SharedresourceTest",
    "SharedresourceauditedpermissionsObject",
    "SharedresourceauditedpermissionsState",
    "SharedresourceauditedpermissionsTest",
    "SharedresourceeffectiverightsObject",
    "SharedresourceeffectiverightsState",
    "SharedresourceeffectiverightsTest",
    "SidObject",
    "SidSidObject",
    "SidSidState",
    "SidSidTest",
    "SidState",
    "SidTest",
    "SystemmetricObject",
    "SystemmetricState",
    "SystemmetricTest",
    "UacObject",
    "UacState",
    "UacTest",
    "UserObject",
    "UserSid55Object",
    "UserSid55State",
    "UserSid55Test",
    "UserSidObject",
    "UserSidState",
    "UserSidTest",
    "UserState",
    "UserTest",
    "UserrightObject",
    "UserrightState",
    "UserrightTest",
    "VolumeObject",
    "VolumeState",
    "VolumeTest",
    "Wmi57Object",
    "Wmi57State",
    "Wmi57Test",
    "WmiObject",
    "WmiState",
    "WmiTest",
    "WuaupdatesearcherObject",
    "WuaupdatesearcherState",
    "WuaupdatesearcherTest",
    "CanonicalizationMethod",
    "CanonicalizationMethodType",
    "DsakeyValue",
    "DsakeyValueType",
    "DigestMethod",
    "DigestMethodType",
    "DigestValue",
    "KeyInfo",
    "KeyInfoType",
    "KeyName",
    "KeyValue",
    "KeyValueType",
    "Manifest",
    "ManifestType",
    "MgmtData",
    "XmldsigCoreObject",
    "XmldsigCoreObjectType",
    "Pgpdata",
    "PgpdataType",
    "RsakeyValue",
    "RsakeyValueType",
    "Reference",
    "XmldsigCoreReferenceType",
    "RetrievalMethod",
    "RetrievalMethodType",
    "Spkidata",
    "SpkidataType",
    "Signature",
    "SignatureMethod",
    "SignatureMethodType",
    "SignatureProperties",
    "SignaturePropertiesType",
    "SignatureProperty",
    "SignaturePropertyType",
    "SignatureType",
    "SignatureValue",
    "SignatureValueType",
    "SignedInfo",
    "SignedInfoType",
    "Transform",
    "TransformType",
    "Transforms",
    "TransformsType",
    "X509Data",
    "X509DataType",
    "X509IssuerSerialType",
]
