id: networking_application_firewall_remote_access
title: Ubuntu 22.04 LTS must have an application firewall installed in order to control
  remote access methods.
discussion: "Remote access services lacking automated controls increase risk and complicate\
  \ access management, so Ubuntu\u202F22.04\u202FLTS (e.g., RDP) must enforce actions\
  \ on unauthorized activity, and automated session controls ensure ongoing compliance\
  \ by enforcing connection rules across servers, workstations, notebooks, smartphones,\
  \ and tablets."
references:
  nist:
    800-53r5:
    - AC-17(01)
  disa:
    cci:
    - CCI-002314
    srg:
    - SRG-OS-000297-GPOS-00115
    disa_stig:
      ubuntu_2204:
      - UBTU-22-251010
      ubuntu_2404:
      - UBTU-24-100300
platforms:
- name: ubuntu_2204
  benchmarks:
  - name: disa_stig
    severity: medium
  enforcement_info:
    check:
      shell: dpkg -s ufw >/dev/null 2>&1
      expected_output: 0
    fix:
      shell: sudo apt-get install ufw
- name: ubuntu_2404
  benchmarks:
  - name: disa_stig
    severity: medium
  enforcement_info:
    check:
      shell: dpkg -l | grep -q '^ii.*ufw'
      expected_output: 0
    fix:
      shell: sudo apt install -y ufw
tags:
- 800-53r5_moderate
- 800-53r5_high
